// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: department.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createDepartment = `-- name: CreateDepartment :one
INSERT INTO departments (name, description)
VALUES ($1, $2)
RETURNING id, name, description, created_at, updated_at
`

type CreateDepartmentParams struct {
	Name        string
	Description string
}

func (q *Queries) CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (Department, error) {
	row := q.db.QueryRowContext(ctx, createDepartment, arg.Name, arg.Description)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDepartment = `-- name: DeleteDepartment :exec
DELETE FROM departments WHERE id = $1
`

func (q *Queries) DeleteDepartment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDepartment, id)
	return err
}

const getDepartment = `-- name: GetDepartment :one
SELECT id, name, description, created_at, updated_at FROM departments WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDepartment(ctx context.Context, id uuid.UUID) (Department, error) {
	row := q.db.QueryRowContext(ctx, getDepartment, id)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDepartments = `-- name: ListDepartments :many
SELECT id, name, description, created_at, updated_at FROM departments ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListDepartmentsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListDepartments(ctx context.Context, arg ListDepartmentsParams) ([]Department, error) {
	rows, err := q.db.QueryContext(ctx, listDepartments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Department
	for rows.Next() {
		var i Department
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDepartment = `-- name: UpdateDepartment :one
UPDATE departments
SET name = $2, description = $3, updated_at = now()
WHERE id = $1
RETURNING id, name, description, created_at, updated_at
`

type UpdateDepartmentParams struct {
	ID          uuid.UUID
	Name        string
	Description string
}

func (q *Queries) UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) (Department, error) {
	row := q.db.QueryRowContext(ctx, updateDepartment, arg.ID, arg.Name, arg.Description)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
