// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: greennote.proto

package greennote

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GreenNoteService_CreateGreenNote_FullMethodName            = "/greennote.GreenNoteService/CreateGreenNote"
	GreenNoteService_GetGreenNote_FullMethodName               = "/greennote.GreenNoteService/GetGreenNote"
	GreenNoteService_ListGreenNotes_FullMethodName             = "/greennote.GreenNoteService/ListGreenNotes"
	GreenNoteService_UpdateGreenNote_FullMethodName            = "/greennote.GreenNoteService/UpdateGreenNote"
	GreenNoteService_CancelGreenNote_FullMethodName            = "/greennote.GreenNoteService/CancelGreenNote"
	GreenNoteService_GetOrganizationProjects_FullMethodName    = "/greennote.GreenNoteService/GetOrganizationProjects"
	GreenNoteService_GetOrganizationVendors_FullMethodName     = "/greennote.GreenNoteService/GetOrganizationVendors"
	GreenNoteService_GetOrganizationDepartments_FullMethodName = "/greennote.GreenNoteService/GetOrganizationDepartments"
)

// GreenNoteServiceClient is the client API for GreenNoteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// =======================
// SERVICE
// =======================
type GreenNoteServiceClient interface {
	// Create
	CreateGreenNote(ctx context.Context, in *CreateGreenNoteRequest, opts ...grpc.CallOption) (*GreenNoteResponse, error)
	// Get full detail by ID
	GetGreenNote(ctx context.Context, in *GetGreenNoteRequest, opts ...grpc.CallOption) (*GreenNoteDetailResponse, error)
	// List (light view)
	ListGreenNotes(ctx context.Context, in *ListGreenNotesRequest, opts ...grpc.CallOption) (*ListGreenNotesResponse, error)
	// Update
	UpdateGreenNote(ctx context.Context, in *UpdateGreenNoteRequest, opts ...grpc.CallOption) (*GreenNoteResponse, error)
	// Cancel (not delete)
	CancelGreenNote(ctx context.Context, in *CancelGreenNoteRequest, opts ...grpc.CallOption) (*GreenNoteResponse, error)
	// Get projects for the logged-in user's organization
	GetOrganizationProjects(ctx context.Context, in *GetOrganizationProjectsRequest, opts ...grpc.CallOption) (*GetOrganizationProjectsResponse, error)
	// Get vendors (suppliers) for the logged-in user's organization
	GetOrganizationVendors(ctx context.Context, in *GetOrganizationVendorsRequest, opts ...grpc.CallOption) (*GetOrganizationVendorsResponse, error)
	// Get departments for the logged-in user's organization
	GetOrganizationDepartments(ctx context.Context, in *GetOrganizationDepartmentsRequest, opts ...grpc.CallOption) (*GetOrganizationDepartmentsResponse, error)
}

type greenNoteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGreenNoteServiceClient(cc grpc.ClientConnInterface) GreenNoteServiceClient {
	return &greenNoteServiceClient{cc}
}

func (c *greenNoteServiceClient) CreateGreenNote(ctx context.Context, in *CreateGreenNoteRequest, opts ...grpc.CallOption) (*GreenNoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GreenNoteResponse)
	err := c.cc.Invoke(ctx, GreenNoteService_CreateGreenNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greenNoteServiceClient) GetGreenNote(ctx context.Context, in *GetGreenNoteRequest, opts ...grpc.CallOption) (*GreenNoteDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GreenNoteDetailResponse)
	err := c.cc.Invoke(ctx, GreenNoteService_GetGreenNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greenNoteServiceClient) ListGreenNotes(ctx context.Context, in *ListGreenNotesRequest, opts ...grpc.CallOption) (*ListGreenNotesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGreenNotesResponse)
	err := c.cc.Invoke(ctx, GreenNoteService_ListGreenNotes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greenNoteServiceClient) UpdateGreenNote(ctx context.Context, in *UpdateGreenNoteRequest, opts ...grpc.CallOption) (*GreenNoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GreenNoteResponse)
	err := c.cc.Invoke(ctx, GreenNoteService_UpdateGreenNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greenNoteServiceClient) CancelGreenNote(ctx context.Context, in *CancelGreenNoteRequest, opts ...grpc.CallOption) (*GreenNoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GreenNoteResponse)
	err := c.cc.Invoke(ctx, GreenNoteService_CancelGreenNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greenNoteServiceClient) GetOrganizationProjects(ctx context.Context, in *GetOrganizationProjectsRequest, opts ...grpc.CallOption) (*GetOrganizationProjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrganizationProjectsResponse)
	err := c.cc.Invoke(ctx, GreenNoteService_GetOrganizationProjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greenNoteServiceClient) GetOrganizationVendors(ctx context.Context, in *GetOrganizationVendorsRequest, opts ...grpc.CallOption) (*GetOrganizationVendorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrganizationVendorsResponse)
	err := c.cc.Invoke(ctx, GreenNoteService_GetOrganizationVendors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greenNoteServiceClient) GetOrganizationDepartments(ctx context.Context, in *GetOrganizationDepartmentsRequest, opts ...grpc.CallOption) (*GetOrganizationDepartmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrganizationDepartmentsResponse)
	err := c.cc.Invoke(ctx, GreenNoteService_GetOrganizationDepartments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreenNoteServiceServer is the server API for GreenNoteService service.
// All implementations must embed UnimplementedGreenNoteServiceServer
// for forward compatibility.
//
// =======================
// SERVICE
// =======================
type GreenNoteServiceServer interface {
	// Create
	CreateGreenNote(context.Context, *CreateGreenNoteRequest) (*GreenNoteResponse, error)
	// Get full detail by ID
	GetGreenNote(context.Context, *GetGreenNoteRequest) (*GreenNoteDetailResponse, error)
	// List (light view)
	ListGreenNotes(context.Context, *ListGreenNotesRequest) (*ListGreenNotesResponse, error)
	// Update
	UpdateGreenNote(context.Context, *UpdateGreenNoteRequest) (*GreenNoteResponse, error)
	// Cancel (not delete)
	CancelGreenNote(context.Context, *CancelGreenNoteRequest) (*GreenNoteResponse, error)
	// Get projects for the logged-in user's organization
	GetOrganizationProjects(context.Context, *GetOrganizationProjectsRequest) (*GetOrganizationProjectsResponse, error)
	// Get vendors (suppliers) for the logged-in user's organization
	GetOrganizationVendors(context.Context, *GetOrganizationVendorsRequest) (*GetOrganizationVendorsResponse, error)
	// Get departments for the logged-in user's organization
	GetOrganizationDepartments(context.Context, *GetOrganizationDepartmentsRequest) (*GetOrganizationDepartmentsResponse, error)
	mustEmbedUnimplementedGreenNoteServiceServer()
}

// UnimplementedGreenNoteServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGreenNoteServiceServer struct{}

func (UnimplementedGreenNoteServiceServer) CreateGreenNote(context.Context, *CreateGreenNoteRequest) (*GreenNoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGreenNote not implemented")
}
func (UnimplementedGreenNoteServiceServer) GetGreenNote(context.Context, *GetGreenNoteRequest) (*GreenNoteDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGreenNote not implemented")
}
func (UnimplementedGreenNoteServiceServer) ListGreenNotes(context.Context, *ListGreenNotesRequest) (*ListGreenNotesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListGreenNotes not implemented")
}
func (UnimplementedGreenNoteServiceServer) UpdateGreenNote(context.Context, *UpdateGreenNoteRequest) (*GreenNoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateGreenNote not implemented")
}
func (UnimplementedGreenNoteServiceServer) CancelGreenNote(context.Context, *CancelGreenNoteRequest) (*GreenNoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelGreenNote not implemented")
}
func (UnimplementedGreenNoteServiceServer) GetOrganizationProjects(context.Context, *GetOrganizationProjectsRequest) (*GetOrganizationProjectsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrganizationProjects not implemented")
}
func (UnimplementedGreenNoteServiceServer) GetOrganizationVendors(context.Context, *GetOrganizationVendorsRequest) (*GetOrganizationVendorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrganizationVendors not implemented")
}
func (UnimplementedGreenNoteServiceServer) GetOrganizationDepartments(context.Context, *GetOrganizationDepartmentsRequest) (*GetOrganizationDepartmentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrganizationDepartments not implemented")
}
func (UnimplementedGreenNoteServiceServer) mustEmbedUnimplementedGreenNoteServiceServer() {}
func (UnimplementedGreenNoteServiceServer) testEmbeddedByValue()                          {}

// UnsafeGreenNoteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreenNoteServiceServer will
// result in compilation errors.
type UnsafeGreenNoteServiceServer interface {
	mustEmbedUnimplementedGreenNoteServiceServer()
}

func RegisterGreenNoteServiceServer(s grpc.ServiceRegistrar, srv GreenNoteServiceServer) {
	// If the following call pancis, it indicates UnimplementedGreenNoteServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GreenNoteService_ServiceDesc, srv)
}

func _GreenNoteService_CreateGreenNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGreenNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreenNoteServiceServer).CreateGreenNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GreenNoteService_CreateGreenNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreenNoteServiceServer).CreateGreenNote(ctx, req.(*CreateGreenNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GreenNoteService_GetGreenNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGreenNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreenNoteServiceServer).GetGreenNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GreenNoteService_GetGreenNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreenNoteServiceServer).GetGreenNote(ctx, req.(*GetGreenNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GreenNoteService_ListGreenNotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGreenNotesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreenNoteServiceServer).ListGreenNotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GreenNoteService_ListGreenNotes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreenNoteServiceServer).ListGreenNotes(ctx, req.(*ListGreenNotesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GreenNoteService_UpdateGreenNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGreenNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreenNoteServiceServer).UpdateGreenNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GreenNoteService_UpdateGreenNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreenNoteServiceServer).UpdateGreenNote(ctx, req.(*UpdateGreenNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GreenNoteService_CancelGreenNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelGreenNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreenNoteServiceServer).CancelGreenNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GreenNoteService_CancelGreenNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreenNoteServiceServer).CancelGreenNote(ctx, req.(*CancelGreenNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GreenNoteService_GetOrganizationProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrganizationProjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreenNoteServiceServer).GetOrganizationProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GreenNoteService_GetOrganizationProjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreenNoteServiceServer).GetOrganizationProjects(ctx, req.(*GetOrganizationProjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GreenNoteService_GetOrganizationVendors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrganizationVendorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreenNoteServiceServer).GetOrganizationVendors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GreenNoteService_GetOrganizationVendors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreenNoteServiceServer).GetOrganizationVendors(ctx, req.(*GetOrganizationVendorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GreenNoteService_GetOrganizationDepartments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrganizationDepartmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreenNoteServiceServer).GetOrganizationDepartments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GreenNoteService_GetOrganizationDepartments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreenNoteServiceServer).GetOrganizationDepartments(ctx, req.(*GetOrganizationDepartmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GreenNoteService_ServiceDesc is the grpc.ServiceDesc for GreenNoteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GreenNoteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "greennote.GreenNoteService",
	HandlerType: (*GreenNoteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGreenNote",
			Handler:    _GreenNoteService_CreateGreenNote_Handler,
		},
		{
			MethodName: "GetGreenNote",
			Handler:    _GreenNoteService_GetGreenNote_Handler,
		},
		{
			MethodName: "ListGreenNotes",
			Handler:    _GreenNoteService_ListGreenNotes_Handler,
		},
		{
			MethodName: "UpdateGreenNote",
			Handler:    _GreenNoteService_UpdateGreenNote_Handler,
		},
		{
			MethodName: "CancelGreenNote",
			Handler:    _GreenNoteService_CancelGreenNote_Handler,
		},
		{
			MethodName: "GetOrganizationProjects",
			Handler:    _GreenNoteService_GetOrganizationProjects_Handler,
		},
		{
			MethodName: "GetOrganizationVendors",
			Handler:    _GreenNoteService_GetOrganizationVendors_Handler,
		},
		{
			MethodName: "GetOrganizationDepartments",
			Handler:    _GreenNoteService_GetOrganizationDepartments_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "greennote.proto",
}
