// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: potracking.proto

package potracking

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetOrCreatePOTrackingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Provide the PO data to find or create the record
	OrderNo              string  `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	VendorId             int64   `protobuf:"varint,2,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	SupplierId           int64   `protobuf:"varint,3,opt,name=supplier_id,json=supplierId,proto3" json:"supplier_id,omitempty"`
	OrderDate            string  `protobuf:"bytes,4,opt,name=order_date,json=orderDate,proto3" json:"order_date,omitempty"` // ISO-8601 string recommended, e.g. "2025-11-13"
	TotalAmount          float64 `protobuf:"fixed64,5,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	BriefOfGoodsServices string  `protobuf:"bytes,6,opt,name=brief_of_goods_services,json=briefOfGoodsServices,proto3" json:"brief_of_goods_services,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetOrCreatePOTrackingRequest) Reset() {
	*x = GetOrCreatePOTrackingRequest{}
	mi := &file_potracking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrCreatePOTrackingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrCreatePOTrackingRequest) ProtoMessage() {}

func (x *GetOrCreatePOTrackingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_potracking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrCreatePOTrackingRequest.ProtoReflect.Descriptor instead.
func (*GetOrCreatePOTrackingRequest) Descriptor() ([]byte, []int) {
	return file_potracking_proto_rawDescGZIP(), []int{0}
}

func (x *GetOrCreatePOTrackingRequest) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *GetOrCreatePOTrackingRequest) GetVendorId() int64 {
	if x != nil {
		return x.VendorId
	}
	return 0
}

func (x *GetOrCreatePOTrackingRequest) GetSupplierId() int64 {
	if x != nil {
		return x.SupplierId
	}
	return 0
}

func (x *GetOrCreatePOTrackingRequest) GetOrderDate() string {
	if x != nil {
		return x.OrderDate
	}
	return ""
}

func (x *GetOrCreatePOTrackingRequest) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *GetOrCreatePOTrackingRequest) GetBriefOfGoodsServices() string {
	if x != nil {
		return x.BriefOfGoodsServices
	}
	return ""
}

type GetPORequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPORequest) Reset() {
	*x = GetPORequest{}
	mi := &file_potracking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPORequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPORequest) ProtoMessage() {}

func (x *GetPORequest) ProtoReflect() protoreflect.Message {
	mi := &file_potracking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPORequest.ProtoReflect.Descriptor instead.
func (*GetPORequest) Descriptor() ([]byte, []int) {
	return file_potracking_proto_rawDescGZIP(), []int{1}
}

func (x *GetPORequest) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

type CalculateExpendituresRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	InvoiceValue  float64                `protobuf:"fixed64,2,opt,name=invoice_value,json=invoiceValue,proto3" json:"invoice_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateExpendituresRequest) Reset() {
	*x = CalculateExpendituresRequest{}
	mi := &file_potracking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateExpendituresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateExpendituresRequest) ProtoMessage() {}

func (x *CalculateExpendituresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_potracking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateExpendituresRequest.ProtoReflect.Descriptor instead.
func (*CalculateExpendituresRequest) Descriptor() ([]byte, []int) {
	return file_potracking_proto_rawDescGZIP(), []int{2}
}

func (x *CalculateExpendituresRequest) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *CalculateExpendituresRequest) GetInvoiceValue() float64 {
	if x != nil {
		return x.InvoiceValue
	}
	return 0
}

type UpdatePOUtilizationRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	PoTrackingId int64                  `protobuf:"varint,1,opt,name=po_tracking_id,json=poTrackingId,proto3" json:"po_tracking_id,omitempty"`
	// optional: include green note id if needed
	GreenNoteId   int64 `protobuf:"varint,2,opt,name=green_note_id,json=greenNoteId,proto3" json:"green_note_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePOUtilizationRequest) Reset() {
	*x = UpdatePOUtilizationRequest{}
	mi := &file_potracking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePOUtilizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePOUtilizationRequest) ProtoMessage() {}

func (x *UpdatePOUtilizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_potracking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePOUtilizationRequest.ProtoReflect.Descriptor instead.
func (*UpdatePOUtilizationRequest) Descriptor() ([]byte, []int) {
	return file_potracking_proto_rawDescGZIP(), []int{3}
}

func (x *UpdatePOUtilizationRequest) GetPoTrackingId() int64 {
	if x != nil {
		return x.PoTrackingId
	}
	return 0
}

func (x *UpdatePOUtilizationRequest) GetGreenNoteId() int64 {
	if x != nil {
		return x.GreenNoteId
	}
	return 0
}

type ValidatePOBudgetRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	OrderNo            string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	InvoiceValue       float64                `protobuf:"fixed64,2,opt,name=invoice_value,json=invoiceValue,proto3" json:"invoice_value,omitempty"`
	ExcludeGreenNoteId int64                  `protobuf:"varint,3,opt,name=exclude_green_note_id,json=excludeGreenNoteId,proto3" json:"exclude_green_note_id,omitempty"` // optional, used when updating an existing green note
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ValidatePOBudgetRequest) Reset() {
	*x = ValidatePOBudgetRequest{}
	mi := &file_potracking_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatePOBudgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatePOBudgetRequest) ProtoMessage() {}

func (x *ValidatePOBudgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_potracking_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatePOBudgetRequest.ProtoReflect.Descriptor instead.
func (*ValidatePOBudgetRequest) Descriptor() ([]byte, []int) {
	return file_potracking_proto_rawDescGZIP(), []int{4}
}

func (x *ValidatePOBudgetRequest) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *ValidatePOBudgetRequest) GetInvoiceValue() float64 {
	if x != nil {
		return x.InvoiceValue
	}
	return 0
}

func (x *ValidatePOBudgetRequest) GetExcludeGreenNoteId() int64 {
	if x != nil {
		return x.ExcludeGreenNoteId
	}
	return 0
}

type POTrackingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PoTracking    *POTracking            `protobuf:"bytes,1,opt,name=po_tracking,json=poTracking,proto3" json:"po_tracking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *POTrackingResponse) Reset() {
	*x = POTrackingResponse{}
	mi := &file_potracking_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *POTrackingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*POTrackingResponse) ProtoMessage() {}

func (x *POTrackingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_potracking_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use POTrackingResponse.ProtoReflect.Descriptor instead.
func (*POTrackingResponse) Descriptor() ([]byte, []int) {
	return file_potracking_proto_rawDescGZIP(), []int{5}
}

func (x *POTrackingResponse) GetPoTracking() *POTracking {
	if x != nil {
		return x.PoTracking
	}
	return nil
}

type CalculateExpendituresResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Matches calculateExpenditures() return array in PHP
	ActualExpenditure     string  `protobuf:"bytes,1,opt,name=actual_expenditure,json=actualExpenditure,proto3" json:"actual_expenditure,omitempty"`               // formatted string e.g. "1000.00"
	BudgetExpenditure     string  `protobuf:"bytes,2,opt,name=budget_expenditure,json=budgetExpenditure,proto3" json:"budget_expenditure,omitempty"`               // formatted string e.g. "500.00"
	ExpenditureOverBudget string  `protobuf:"bytes,3,opt,name=expenditure_over_budget,json=expenditureOverBudget,proto3" json:"expenditure_over_budget,omitempty"` // "Yes" / "No"
	RemainingBudget       string  `protobuf:"bytes,4,opt,name=remaining_budget,json=remainingBudget,proto3" json:"remaining_budget,omitempty"`                     // formatted string
	UtilizationPercentage float64 `protobuf:"fixed64,5,opt,name=utilization_percentage,json=utilizationPercentage,proto3" json:"utilization_percentage,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CalculateExpendituresResponse) Reset() {
	*x = CalculateExpendituresResponse{}
	mi := &file_potracking_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateExpendituresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateExpendituresResponse) ProtoMessage() {}

func (x *CalculateExpendituresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_potracking_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateExpendituresResponse.ProtoReflect.Descriptor instead.
func (*CalculateExpendituresResponse) Descriptor() ([]byte, []int) {
	return file_potracking_proto_rawDescGZIP(), []int{6}
}

func (x *CalculateExpendituresResponse) GetActualExpenditure() string {
	if x != nil {
		return x.ActualExpenditure
	}
	return ""
}

func (x *CalculateExpendituresResponse) GetBudgetExpenditure() string {
	if x != nil {
		return x.BudgetExpenditure
	}
	return ""
}

func (x *CalculateExpendituresResponse) GetExpenditureOverBudget() string {
	if x != nil {
		return x.ExpenditureOverBudget
	}
	return ""
}

func (x *CalculateExpendituresResponse) GetRemainingBudget() string {
	if x != nil {
		return x.RemainingBudget
	}
	return ""
}

func (x *CalculateExpendituresResponse) GetUtilizationPercentage() float64 {
	if x != nil {
		return x.UtilizationPercentage
	}
	return 0
}

type ValidatePOBudgetResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Valid              bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Message            string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	PoTracking         *POTracking            `protobuf:"bytes,3,opt,name=po_tracking,json=poTracking,proto3" json:"po_tracking,omitempty"`
	CurrentUtilization float64                `protobuf:"fixed64,4,opt,name=current_utilization,json=currentUtilization,proto3" json:"current_utilization,omitempty"`
	RemainingBudget    float64                `protobuf:"fixed64,5,opt,name=remaining_budget,json=remainingBudget,proto3" json:"remaining_budget,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ValidatePOBudgetResponse) Reset() {
	*x = ValidatePOBudgetResponse{}
	mi := &file_potracking_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatePOBudgetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatePOBudgetResponse) ProtoMessage() {}

func (x *ValidatePOBudgetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_potracking_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatePOBudgetResponse.ProtoReflect.Descriptor instead.
func (*ValidatePOBudgetResponse) Descriptor() ([]byte, []int) {
	return file_potracking_proto_rawDescGZIP(), []int{7}
}

func (x *ValidatePOBudgetResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidatePOBudgetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ValidatePOBudgetResponse) GetPoTracking() *POTracking {
	if x != nil {
		return x.PoTracking
	}
	return nil
}

func (x *ValidatePOBudgetResponse) GetCurrentUtilization() float64 {
	if x != nil {
		return x.CurrentUtilization
	}
	return 0
}

func (x *ValidatePOBudgetResponse) GetRemainingBudget() float64 {
	if x != nil {
		return x.RemainingBudget
	}
	return 0
}

type GetPOSummaryResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Exists  bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// present when exists == true:
	OrderNo               string  `protobuf:"bytes,3,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	OrderValue            float64 `protobuf:"fixed64,4,opt,name=order_value,json=orderValue,proto3" json:"order_value,omitempty"`
	TotalUtilized         float64 `protobuf:"fixed64,5,opt,name=total_utilized,json=totalUtilized,proto3" json:"total_utilized,omitempty"`
	RemainingBudget       float64 `protobuf:"fixed64,6,opt,name=remaining_budget,json=remainingBudget,proto3" json:"remaining_budget,omitempty"`
	UtilizationPercentage float64 `protobuf:"fixed64,7,opt,name=utilization_percentage,json=utilizationPercentage,proto3" json:"utilization_percentage,omitempty"`
	GreenNotesCount       int32   `protobuf:"varint,8,opt,name=green_notes_count,json=greenNotesCount,proto3" json:"green_notes_count,omitempty"`
	Status                string  `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	Vendor                string  `protobuf:"bytes,10,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Supplier              string  `protobuf:"bytes,11,opt,name=supplier,proto3" json:"supplier,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetPOSummaryResponse) Reset() {
	*x = GetPOSummaryResponse{}
	mi := &file_potracking_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPOSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPOSummaryResponse) ProtoMessage() {}

func (x *GetPOSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_potracking_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPOSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetPOSummaryResponse) Descriptor() ([]byte, []int) {
	return file_potracking_proto_rawDescGZIP(), []int{8}
}

func (x *GetPOSummaryResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *GetPOSummaryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetPOSummaryResponse) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *GetPOSummaryResponse) GetOrderValue() float64 {
	if x != nil {
		return x.OrderValue
	}
	return 0
}

func (x *GetPOSummaryResponse) GetTotalUtilized() float64 {
	if x != nil {
		return x.TotalUtilized
	}
	return 0
}

func (x *GetPOSummaryResponse) GetRemainingBudget() float64 {
	if x != nil {
		return x.RemainingBudget
	}
	return 0
}

func (x *GetPOSummaryResponse) GetUtilizationPercentage() float64 {
	if x != nil {
		return x.UtilizationPercentage
	}
	return 0
}

func (x *GetPOSummaryResponse) GetGreenNotesCount() int32 {
	if x != nil {
		return x.GreenNotesCount
	}
	return 0
}

func (x *GetPOSummaryResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetPOSummaryResponse) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *GetPOSummaryResponse) GetSupplier() string {
	if x != nil {
		return x.Supplier
	}
	return ""
}

type RecalculateAllResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RecordsUpdated int32                  `protobuf:"varint,1,opt,name=records_updated,json=recordsUpdated,proto3" json:"records_updated,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RecalculateAllResponse) Reset() {
	*x = RecalculateAllResponse{}
	mi := &file_potracking_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecalculateAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecalculateAllResponse) ProtoMessage() {}

func (x *RecalculateAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_potracking_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecalculateAllResponse.ProtoReflect.Descriptor instead.
func (*RecalculateAllResponse) Descriptor() ([]byte, []int) {
	return file_potracking_proto_rawDescGZIP(), []int{9}
}

func (x *RecalculateAllResponse) GetRecordsUpdated() int32 {
	if x != nil {
		return x.RecordsUpdated
	}
	return 0
}

type POTracking struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderNo               string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	VendorId              int64                  `protobuf:"varint,3,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	SupplierId            int64                  `protobuf:"varint,4,opt,name=supplier_id,json=supplierId,proto3" json:"supplier_id,omitempty"`
	OrderDate             string                 `protobuf:"bytes,5,opt,name=order_date,json=orderDate,proto3" json:"order_date,omitempty"` // ISO-8601
	OrderValue            float64                `protobuf:"fixed64,6,opt,name=order_value,json=orderValue,proto3" json:"order_value,omitempty"`
	TotalUtilized         float64                `protobuf:"fixed64,7,opt,name=total_utilized,json=totalUtilized,proto3" json:"total_utilized,omitempty"`
	RemainingBudget       float64                `protobuf:"fixed64,8,opt,name=remaining_budget,json=remainingBudget,proto3" json:"remaining_budget,omitempty"`
	GreenNotesCount       int32                  `protobuf:"varint,9,opt,name=green_notes_count,json=greenNotesCount,proto3" json:"green_notes_count,omitempty"`
	Description           string                 `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	Status                string                 `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	UtilizationPercentage float64                `protobuf:"fixed64,12,opt,name=utilization_percentage,json=utilizationPercentage,proto3" json:"utilization_percentage,omitempty"`
	Vendor                *VendorInfo            `protobuf:"bytes,13,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Supplier              *SupplierInfo          `protobuf:"bytes,14,opt,name=supplier,proto3" json:"supplier,omitempty"`
	GreenNotes            []*GreenNoteInfo       `protobuf:"bytes,15,rep,name=green_notes,json=greenNotes,proto3" json:"green_notes,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *POTracking) Reset() {
	*x = POTracking{}
	mi := &file_potracking_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *POTracking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*POTracking) ProtoMessage() {}

func (x *POTracking) ProtoReflect() protoreflect.Message {
	mi := &file_potracking_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use POTracking.ProtoReflect.Descriptor instead.
func (*POTracking) Descriptor() ([]byte, []int) {
	return file_potracking_proto_rawDescGZIP(), []int{10}
}

func (x *POTracking) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *POTracking) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *POTracking) GetVendorId() int64 {
	if x != nil {
		return x.VendorId
	}
	return 0
}

func (x *POTracking) GetSupplierId() int64 {
	if x != nil {
		return x.SupplierId
	}
	return 0
}

func (x *POTracking) GetOrderDate() string {
	if x != nil {
		return x.OrderDate
	}
	return ""
}

func (x *POTracking) GetOrderValue() float64 {
	if x != nil {
		return x.OrderValue
	}
	return 0
}

func (x *POTracking) GetTotalUtilized() float64 {
	if x != nil {
		return x.TotalUtilized
	}
	return 0
}

func (x *POTracking) GetRemainingBudget() float64 {
	if x != nil {
		return x.RemainingBudget
	}
	return 0
}

func (x *POTracking) GetGreenNotesCount() int32 {
	if x != nil {
		return x.GreenNotesCount
	}
	return 0
}

func (x *POTracking) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *POTracking) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *POTracking) GetUtilizationPercentage() float64 {
	if x != nil {
		return x.UtilizationPercentage
	}
	return 0
}

func (x *POTracking) GetVendor() *VendorInfo {
	if x != nil {
		return x.Vendor
	}
	return nil
}

func (x *POTracking) GetSupplier() *SupplierInfo {
	if x != nil {
		return x.Supplier
	}
	return nil
}

func (x *POTracking) GetGreenNotes() []*GreenNoteInfo {
	if x != nil {
		return x.GreenNotes
	}
	return nil
}

type VendorInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	VendorName    string                 `protobuf:"bytes,2,opt,name=vendor_name,json=vendorName,proto3" json:"vendor_name,omitempty"`
	Project       string                 `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VendorInfo) Reset() {
	*x = VendorInfo{}
	mi := &file_potracking_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VendorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VendorInfo) ProtoMessage() {}

func (x *VendorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_potracking_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VendorInfo.ProtoReflect.Descriptor instead.
func (*VendorInfo) Descriptor() ([]byte, []int) {
	return file_potracking_proto_rawDescGZIP(), []int{11}
}

func (x *VendorInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VendorInfo) GetVendorName() string {
	if x != nil {
		return x.VendorName
	}
	return ""
}

func (x *VendorInfo) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

type SupplierInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SupplierName  string                 `protobuf:"bytes,2,opt,name=supplier_name,json=supplierName,proto3" json:"supplier_name,omitempty"`
	VendorName    string                 `protobuf:"bytes,3,opt,name=vendor_name,json=vendorName,proto3" json:"vendor_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupplierInfo) Reset() {
	*x = SupplierInfo{}
	mi := &file_potracking_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupplierInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupplierInfo) ProtoMessage() {}

func (x *SupplierInfo) ProtoReflect() protoreflect.Message {
	mi := &file_potracking_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupplierInfo.ProtoReflect.Descriptor instead.
func (*SupplierInfo) Descriptor() ([]byte, []int) {
	return file_potracking_proto_rawDescGZIP(), []int{12}
}

func (x *SupplierInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SupplierInfo) GetSupplierName() string {
	if x != nil {
		return x.SupplierName
	}
	return ""
}

func (x *SupplierInfo) GetVendorName() string {
	if x != nil {
		return x.VendorName
	}
	return ""
}

type GreenNoteInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NoteNo        string                 `protobuf:"bytes,2,opt,name=note_no,json=noteNo,proto3" json:"note_no,omitempty"`
	InvoiceValue  float64                `protobuf:"fixed64,3,opt,name=invoice_value,json=invoiceValue,proto3" json:"invoice_value,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GreenNoteInfo) Reset() {
	*x = GreenNoteInfo{}
	mi := &file_potracking_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GreenNoteInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreenNoteInfo) ProtoMessage() {}

func (x *GreenNoteInfo) ProtoReflect() protoreflect.Message {
	mi := &file_potracking_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreenNoteInfo.ProtoReflect.Descriptor instead.
func (*GreenNoteInfo) Descriptor() ([]byte, []int) {
	return file_potracking_proto_rawDescGZIP(), []int{13}
}

func (x *GreenNoteInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GreenNoteInfo) GetNoteNo() string {
	if x != nil {
		return x.NoteNo
	}
	return ""
}

func (x *GreenNoteInfo) GetInvoiceValue() float64 {
	if x != nil {
		return x.InvoiceValue
	}
	return 0
}

func (x *GreenNoteInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GreenNoteInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_potracking_proto protoreflect.FileDescriptor

const file_potracking_proto_rawDesc = "" +
	"\n" +
	"\x10potracking.proto\x12\n" +
	"potracking\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\"\xf0\x01\n" +
	"\x1cGetOrCreatePOTrackingRequest\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x1b\n" +
	"\tvendor_id\x18\x02 \x01(\x03R\bvendorId\x12\x1f\n" +
	"\vsupplier_id\x18\x03 \x01(\x03R\n" +
	"supplierId\x12\x1d\n" +
	"\n" +
	"order_date\x18\x04 \x01(\tR\torderDate\x12!\n" +
	"\ftotal_amount\x18\x05 \x01(\x01R\vtotalAmount\x125\n" +
	"\x17brief_of_goods_services\x18\x06 \x01(\tR\x14briefOfGoodsServices\")\n" +
	"\fGetPORequest\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\"^\n" +
	"\x1cCalculateExpendituresRequest\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12#\n" +
	"\rinvoice_value\x18\x02 \x01(\x01R\finvoiceValue\"f\n" +
	"\x1aUpdatePOUtilizationRequest\x12$\n" +
	"\x0epo_tracking_id\x18\x01 \x01(\x03R\fpoTrackingId\x12\"\n" +
	"\rgreen_note_id\x18\x02 \x01(\x03R\vgreenNoteId\"\x8c\x01\n" +
	"\x17ValidatePOBudgetRequest\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12#\n" +
	"\rinvoice_value\x18\x02 \x01(\x01R\finvoiceValue\x121\n" +
	"\x15exclude_green_note_id\x18\x03 \x01(\x03R\x12excludeGreenNoteId\"M\n" +
	"\x12POTrackingResponse\x127\n" +
	"\vpo_tracking\x18\x01 \x01(\v2\x16.potracking.POTrackingR\n" +
	"poTracking\"\x97\x02\n" +
	"\x1dCalculateExpendituresResponse\x12-\n" +
	"\x12actual_expenditure\x18\x01 \x01(\tR\x11actualExpenditure\x12-\n" +
	"\x12budget_expenditure\x18\x02 \x01(\tR\x11budgetExpenditure\x126\n" +
	"\x17expenditure_over_budget\x18\x03 \x01(\tR\x15expenditureOverBudget\x12)\n" +
	"\x10remaining_budget\x18\x04 \x01(\tR\x0fremainingBudget\x125\n" +
	"\x16utilization_percentage\x18\x05 \x01(\x01R\x15utilizationPercentage\"\xdf\x01\n" +
	"\x18ValidatePOBudgetResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x127\n" +
	"\vpo_tracking\x18\x03 \x01(\v2\x16.potracking.POTrackingR\n" +
	"poTracking\x12/\n" +
	"\x13current_utilization\x18\x04 \x01(\x01R\x12currentUtilization\x12)\n" +
	"\x10remaining_budget\x18\x05 \x01(\x01R\x0fremainingBudget\"\x85\x03\n" +
	"\x14GetPOSummaryResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\border_no\x18\x03 \x01(\tR\aorderNo\x12\x1f\n" +
	"\vorder_value\x18\x04 \x01(\x01R\n" +
	"orderValue\x12%\n" +
	"\x0etotal_utilized\x18\x05 \x01(\x01R\rtotalUtilized\x12)\n" +
	"\x10remaining_budget\x18\x06 \x01(\x01R\x0fremainingBudget\x125\n" +
	"\x16utilization_percentage\x18\a \x01(\x01R\x15utilizationPercentage\x12*\n" +
	"\x11green_notes_count\x18\b \x01(\x05R\x0fgreenNotesCount\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12\x16\n" +
	"\x06vendor\x18\n" +
	" \x01(\tR\x06vendor\x12\x1a\n" +
	"\bsupplier\x18\v \x01(\tR\bsupplier\"A\n" +
	"\x16RecalculateAllResponse\x12'\n" +
	"\x0frecords_updated\x18\x01 \x01(\x05R\x0erecordsUpdated\"\xc6\x04\n" +
	"\n" +
	"POTracking\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\x12\x1b\n" +
	"\tvendor_id\x18\x03 \x01(\x03R\bvendorId\x12\x1f\n" +
	"\vsupplier_id\x18\x04 \x01(\x03R\n" +
	"supplierId\x12\x1d\n" +
	"\n" +
	"order_date\x18\x05 \x01(\tR\torderDate\x12\x1f\n" +
	"\vorder_value\x18\x06 \x01(\x01R\n" +
	"orderValue\x12%\n" +
	"\x0etotal_utilized\x18\a \x01(\x01R\rtotalUtilized\x12)\n" +
	"\x10remaining_budget\x18\b \x01(\x01R\x0fremainingBudget\x12*\n" +
	"\x11green_notes_count\x18\t \x01(\x05R\x0fgreenNotesCount\x12 \n" +
	"\vdescription\x18\n" +
	" \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06status\x125\n" +
	"\x16utilization_percentage\x18\f \x01(\x01R\x15utilizationPercentage\x12.\n" +
	"\x06vendor\x18\r \x01(\v2\x16.potracking.VendorInfoR\x06vendor\x124\n" +
	"\bsupplier\x18\x0e \x01(\v2\x18.potracking.SupplierInfoR\bsupplier\x12:\n" +
	"\vgreen_notes\x18\x0f \x03(\v2\x19.potracking.GreenNoteInfoR\n" +
	"greenNotes\"W\n" +
	"\n" +
	"VendorInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vvendor_name\x18\x02 \x01(\tR\n" +
	"vendorName\x12\x18\n" +
	"\aproject\x18\x03 \x01(\tR\aproject\"d\n" +
	"\fSupplierInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12#\n" +
	"\rsupplier_name\x18\x02 \x01(\tR\fsupplierName\x12\x1f\n" +
	"\vvendor_name\x18\x03 \x01(\tR\n" +
	"vendorName\"\x94\x01\n" +
	"\rGreenNoteInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\anote_no\x18\x02 \x01(\tR\x06noteNo\x12#\n" +
	"\rinvoice_value\x18\x03 \x01(\x01R\finvoiceValue\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt2\xdc\a\n" +
	"\x11POTrackingService\x12\x81\x01\n" +
	"\x15GetOrCreatePOTracking\x12(.potracking.GetOrCreatePOTrackingRequest\x1a\x1e.potracking.POTrackingResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/po-tracking\x12v\n" +
	"\x12GetPOByOrderNumber\x12\x18.potracking.GetPORequest\x1a\x1e.potracking.POTrackingResponse\"&\x82\xd3\xe4\x93\x02 \x12\x1e/api/v1/po-tracking/{order_no}\x12\xa4\x01\n" +
	"\x15CalculateExpenditures\x12(.potracking.CalculateExpendituresRequest\x1a).potracking.CalculateExpendituresResponse\"6\x82\xd3\xe4\x93\x020:\x01*\"+/api/v1/po-tracking/{order_no}/expenditures\x12\x99\x01\n" +
	"\x13UpdatePOUtilization\x12&.potracking.UpdatePOUtilizationRequest\x1a\x16.google.protobuf.Empty\"B\x82\xd3\xe4\x93\x02<:\x01*\"7/api/v1/po-tracking/{po_tracking_id}/update-utilization\x12\x86\x01\n" +
	"\x10ValidatePOBudget\x12#.potracking.ValidatePOBudgetRequest\x1a$.potracking.ValidatePOBudgetResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/api/v1/po-tracking/validate\x12z\n" +
	"\fGetPOSummary\x12\x18.potracking.GetPORequest\x1a .potracking.GetPOSummaryResponse\".\x82\xd3\xe4\x93\x02(\x12&/api/v1/po-tracking/{order_no}/summary\x12\x82\x01\n" +
	"\x18RecalculateAllPOTracking\x12\x16.google.protobuf.Empty\x1a\".potracking.RecalculateAllResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/api/v1/po-tracking/recalculateB%Z#nhit/services/potracking;potrackingb\x06proto3"

var (
	file_potracking_proto_rawDescOnce sync.Once
	file_potracking_proto_rawDescData []byte
)

func file_potracking_proto_rawDescGZIP() []byte {
	file_potracking_proto_rawDescOnce.Do(func() {
		file_potracking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_potracking_proto_rawDesc), len(file_potracking_proto_rawDesc)))
	})
	return file_potracking_proto_rawDescData
}

var file_potracking_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_potracking_proto_goTypes = []any{
	(*GetOrCreatePOTrackingRequest)(nil),  // 0: potracking.GetOrCreatePOTrackingRequest
	(*GetPORequest)(nil),                  // 1: potracking.GetPORequest
	(*CalculateExpendituresRequest)(nil),  // 2: potracking.CalculateExpendituresRequest
	(*UpdatePOUtilizationRequest)(nil),    // 3: potracking.UpdatePOUtilizationRequest
	(*ValidatePOBudgetRequest)(nil),       // 4: potracking.ValidatePOBudgetRequest
	(*POTrackingResponse)(nil),            // 5: potracking.POTrackingResponse
	(*CalculateExpendituresResponse)(nil), // 6: potracking.CalculateExpendituresResponse
	(*ValidatePOBudgetResponse)(nil),      // 7: potracking.ValidatePOBudgetResponse
	(*GetPOSummaryResponse)(nil),          // 8: potracking.GetPOSummaryResponse
	(*RecalculateAllResponse)(nil),        // 9: potracking.RecalculateAllResponse
	(*POTracking)(nil),                    // 10: potracking.POTracking
	(*VendorInfo)(nil),                    // 11: potracking.VendorInfo
	(*SupplierInfo)(nil),                  // 12: potracking.SupplierInfo
	(*GreenNoteInfo)(nil),                 // 13: potracking.GreenNoteInfo
	(*emptypb.Empty)(nil),                 // 14: google.protobuf.Empty
}
var file_potracking_proto_depIdxs = []int32{
	10, // 0: potracking.POTrackingResponse.po_tracking:type_name -> potracking.POTracking
	10, // 1: potracking.ValidatePOBudgetResponse.po_tracking:type_name -> potracking.POTracking
	11, // 2: potracking.POTracking.vendor:type_name -> potracking.VendorInfo
	12, // 3: potracking.POTracking.supplier:type_name -> potracking.SupplierInfo
	13, // 4: potracking.POTracking.green_notes:type_name -> potracking.GreenNoteInfo
	0,  // 5: potracking.POTrackingService.GetOrCreatePOTracking:input_type -> potracking.GetOrCreatePOTrackingRequest
	1,  // 6: potracking.POTrackingService.GetPOByOrderNumber:input_type -> potracking.GetPORequest
	2,  // 7: potracking.POTrackingService.CalculateExpenditures:input_type -> potracking.CalculateExpendituresRequest
	3,  // 8: potracking.POTrackingService.UpdatePOUtilization:input_type -> potracking.UpdatePOUtilizationRequest
	4,  // 9: potracking.POTrackingService.ValidatePOBudget:input_type -> potracking.ValidatePOBudgetRequest
	1,  // 10: potracking.POTrackingService.GetPOSummary:input_type -> potracking.GetPORequest
	14, // 11: potracking.POTrackingService.RecalculateAllPOTracking:input_type -> google.protobuf.Empty
	5,  // 12: potracking.POTrackingService.GetOrCreatePOTracking:output_type -> potracking.POTrackingResponse
	5,  // 13: potracking.POTrackingService.GetPOByOrderNumber:output_type -> potracking.POTrackingResponse
	6,  // 14: potracking.POTrackingService.CalculateExpenditures:output_type -> potracking.CalculateExpendituresResponse
	14, // 15: potracking.POTrackingService.UpdatePOUtilization:output_type -> google.protobuf.Empty
	7,  // 16: potracking.POTrackingService.ValidatePOBudget:output_type -> potracking.ValidatePOBudgetResponse
	8,  // 17: potracking.POTrackingService.GetPOSummary:output_type -> potracking.GetPOSummaryResponse
	9,  // 18: potracking.POTrackingService.RecalculateAllPOTracking:output_type -> potracking.RecalculateAllResponse
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_potracking_proto_init() }
func file_potracking_proto_init() {
	if File_potracking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_potracking_proto_rawDesc), len(file_potracking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_potracking_proto_goTypes,
		DependencyIndexes: file_potracking_proto_depIdxs,
		MessageInfos:      file_potracking_proto_msgTypes,
	}.Build()
	File_potracking_proto = out.File
	file_potracking_proto_goTypes = nil
	file_potracking_proto_depIdxs = nil
}
