// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: vendor.proto

package vendorpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VendorService_CreateVendor_FullMethodName  = "/vendor.VendorService/CreateVendor"
	VendorService_GetVendor_FullMethodName     = "/vendor.VendorService/GetVendor"
	VendorService_ListVendors_FullMethodName   = "/vendor.VendorService/ListVendors"
	VendorService_UpdateVendor_FullMethodName  = "/vendor.VendorService/UpdateVendor"
	VendorService_DeleteVendor_FullMethodName  = "/vendor.VendorService/DeleteVendor"
	VendorService_ImportVendors_FullMethodName = "/vendor.VendorService/ImportVendors"
)

// VendorServiceClient is the client API for VendorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ======================
// Service Definition
// ======================
type VendorServiceClient interface {
	CreateVendor(ctx context.Context, in *CreateVendorRequest, opts ...grpc.CallOption) (*CreateVendorResponse, error)
	GetVendor(ctx context.Context, in *GetVendorRequest, opts ...grpc.CallOption) (*GetVendorResponse, error)
	ListVendors(ctx context.Context, in *ListVendorsRequest, opts ...grpc.CallOption) (*ListVendorsResponse, error)
	UpdateVendor(ctx context.Context, in *UpdateVendorRequest, opts ...grpc.CallOption) (*UpdateVendorResponse, error)
	DeleteVendor(ctx context.Context, in *DeleteVendorRequest, opts ...grpc.CallOption) (*DeleteVendorResponse, error)
	// Import from Excel/CSV
	ImportVendors(ctx context.Context, in *ImportVendorsRequest, opts ...grpc.CallOption) (*ImportVendorsResponse, error)
}

type vendorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVendorServiceClient(cc grpc.ClientConnInterface) VendorServiceClient {
	return &vendorServiceClient{cc}
}

func (c *vendorServiceClient) CreateVendor(ctx context.Context, in *CreateVendorRequest, opts ...grpc.CallOption) (*CreateVendorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateVendorResponse)
	err := c.cc.Invoke(ctx, VendorService_CreateVendor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendorServiceClient) GetVendor(ctx context.Context, in *GetVendorRequest, opts ...grpc.CallOption) (*GetVendorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVendorResponse)
	err := c.cc.Invoke(ctx, VendorService_GetVendor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendorServiceClient) ListVendors(ctx context.Context, in *ListVendorsRequest, opts ...grpc.CallOption) (*ListVendorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVendorsResponse)
	err := c.cc.Invoke(ctx, VendorService_ListVendors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendorServiceClient) UpdateVendor(ctx context.Context, in *UpdateVendorRequest, opts ...grpc.CallOption) (*UpdateVendorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateVendorResponse)
	err := c.cc.Invoke(ctx, VendorService_UpdateVendor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendorServiceClient) DeleteVendor(ctx context.Context, in *DeleteVendorRequest, opts ...grpc.CallOption) (*DeleteVendorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteVendorResponse)
	err := c.cc.Invoke(ctx, VendorService_DeleteVendor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendorServiceClient) ImportVendors(ctx context.Context, in *ImportVendorsRequest, opts ...grpc.CallOption) (*ImportVendorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportVendorsResponse)
	err := c.cc.Invoke(ctx, VendorService_ImportVendors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VendorServiceServer is the server API for VendorService service.
// All implementations must embed UnimplementedVendorServiceServer
// for forward compatibility.
//
// ======================
// Service Definition
// ======================
type VendorServiceServer interface {
	CreateVendor(context.Context, *CreateVendorRequest) (*CreateVendorResponse, error)
	GetVendor(context.Context, *GetVendorRequest) (*GetVendorResponse, error)
	ListVendors(context.Context, *ListVendorsRequest) (*ListVendorsResponse, error)
	UpdateVendor(context.Context, *UpdateVendorRequest) (*UpdateVendorResponse, error)
	DeleteVendor(context.Context, *DeleteVendorRequest) (*DeleteVendorResponse, error)
	// Import from Excel/CSV
	ImportVendors(context.Context, *ImportVendorsRequest) (*ImportVendorsResponse, error)
	mustEmbedUnimplementedVendorServiceServer()
}

// UnimplementedVendorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVendorServiceServer struct{}

func (UnimplementedVendorServiceServer) CreateVendor(context.Context, *CreateVendorRequest) (*CreateVendorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVendor not implemented")
}
func (UnimplementedVendorServiceServer) GetVendor(context.Context, *GetVendorRequest) (*GetVendorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVendor not implemented")
}
func (UnimplementedVendorServiceServer) ListVendors(context.Context, *ListVendorsRequest) (*ListVendorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListVendors not implemented")
}
func (UnimplementedVendorServiceServer) UpdateVendor(context.Context, *UpdateVendorRequest) (*UpdateVendorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateVendor not implemented")
}
func (UnimplementedVendorServiceServer) DeleteVendor(context.Context, *DeleteVendorRequest) (*DeleteVendorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteVendor not implemented")
}
func (UnimplementedVendorServiceServer) ImportVendors(context.Context, *ImportVendorsRequest) (*ImportVendorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportVendors not implemented")
}
func (UnimplementedVendorServiceServer) mustEmbedUnimplementedVendorServiceServer() {}
func (UnimplementedVendorServiceServer) testEmbeddedByValue()                       {}

// UnsafeVendorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VendorServiceServer will
// result in compilation errors.
type UnsafeVendorServiceServer interface {
	mustEmbedUnimplementedVendorServiceServer()
}

func RegisterVendorServiceServer(s grpc.ServiceRegistrar, srv VendorServiceServer) {
	// If the following call pancis, it indicates UnimplementedVendorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VendorService_ServiceDesc, srv)
}

func _VendorService_CreateVendor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVendorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorServiceServer).CreateVendor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VendorService_CreateVendor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorServiceServer).CreateVendor(ctx, req.(*CreateVendorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VendorService_GetVendor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVendorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorServiceServer).GetVendor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VendorService_GetVendor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorServiceServer).GetVendor(ctx, req.(*GetVendorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VendorService_ListVendors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVendorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorServiceServer).ListVendors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VendorService_ListVendors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorServiceServer).ListVendors(ctx, req.(*ListVendorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VendorService_UpdateVendor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateVendorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorServiceServer).UpdateVendor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VendorService_UpdateVendor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorServiceServer).UpdateVendor(ctx, req.(*UpdateVendorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VendorService_DeleteVendor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVendorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorServiceServer).DeleteVendor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VendorService_DeleteVendor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorServiceServer).DeleteVendor(ctx, req.(*DeleteVendorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VendorService_ImportVendors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportVendorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorServiceServer).ImportVendors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VendorService_ImportVendors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorServiceServer).ImportVendors(ctx, req.(*ImportVendorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VendorService_ServiceDesc is the grpc.ServiceDesc for VendorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VendorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vendor.VendorService",
	HandlerType: (*VendorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVendor",
			Handler:    _VendorService_CreateVendor_Handler,
		},
		{
			MethodName: "GetVendor",
			Handler:    _VendorService_GetVendor_Handler,
		},
		{
			MethodName: "ListVendors",
			Handler:    _VendorService_ListVendors_Handler,
		},
		{
			MethodName: "UpdateVendor",
			Handler:    _VendorService_UpdateVendor_Handler,
		},
		{
			MethodName: "DeleteVendor",
			Handler:    _VendorService_DeleteVendor_Handler,
		},
		{
			MethodName: "ImportVendors",
			Handler:    _VendorService_ImportVendors_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vendor.proto",
}
