// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: api/proto/auth.proto

package authpb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserRole int32

const (
	UserRole_USER_ROLE_UNSPECIFIED UserRole = 0
	UserRole_SUPER_ADMIN           UserRole = 1
	UserRole_ADMIN                 UserRole = 2
)

// Enum value maps for UserRole.
var (
	UserRole_name = map[int32]string{
		0: "USER_ROLE_UNSPECIFIED",
		1: "SUPER_ADMIN",
		2: "ADMIN",
	}
	UserRole_value = map[string]int32{
		"USER_ROLE_UNSPECIFIED": 0,
		"SUPER_ADMIN":           1,
		"ADMIN":                 2,
	}
)

func (x UserRole) Enum() *UserRole {
	p := new(UserRole)
	*p = x
	return p
}

func (x UserRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserRole) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_auth_proto_enumTypes[0].Descriptor()
}

func (UserRole) Type() protoreflect.EnumType {
	return &file_api_proto_auth_proto_enumTypes[0]
}

func (x UserRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserRole.Descriptor instead.
func (UserRole) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_auth_proto_rawDescGZIP(), []int{0}
}

type SSOProvider int32

const (
	SSOProvider_SSO_PROVIDER_UNSPECIFIED SSOProvider = 0
	SSOProvider_GOOGLE                   SSOProvider = 1
	SSOProvider_MICROSOFT                SSOProvider = 2
	SSOProvider_OKTA                     SSOProvider = 3
	SSOProvider_KEYCLOAK                 SSOProvider = 4
	SSOProvider_CUSTOM_OIDC              SSOProvider = 5
)

// Enum value maps for SSOProvider.
var (
	SSOProvider_name = map[int32]string{
		0: "SSO_PROVIDER_UNSPECIFIED",
		1: "GOOGLE",
		2: "MICROSOFT",
		3: "OKTA",
		4: "KEYCLOAK",
		5: "CUSTOM_OIDC",
	}
	SSOProvider_value = map[string]int32{
		"SSO_PROVIDER_UNSPECIFIED": 0,
		"GOOGLE":                   1,
		"MICROSOFT":                2,
		"OKTA":                     3,
		"KEYCLOAK":                 4,
		"CUSTOM_OIDC":              5,
	}
)

func (x SSOProvider) Enum() *SSOProvider {
	p := new(SSOProvider)
	*p = x
	return p
}

func (x SSOProvider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SSOProvider) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_auth_proto_enumTypes[1].Descriptor()
}

func (SSOProvider) Type() protoreflect.EnumType {
	return &file_api_proto_auth_proto_enumTypes[1]
}

func (x SSOProvider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SSOProvider.Descriptor instead.
func (SSOProvider) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_auth_proto_rawDescGZIP(), []int{1}
}

// Registration
type RegisterUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Roles         []UserRole             `protobuf:"varint,5,rep,packed,name=roles,proto3,enum=UserRole" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserRequest) Reset() {
	*x = RegisterUserRequest{}
	mi := &file_api_proto_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserRequest) ProtoMessage() {}

func (x *RegisterUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserRequest.ProtoReflect.Descriptor instead.
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterUserRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RegisterUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterUserRequest) GetRoles() []UserRole {
	if x != nil {
		return x.Roles
	}
	return nil
}

type RegisterUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Roles         []UserRole             `protobuf:"varint,4,rep,packed,name=roles,proto3,enum=UserRole" json:"roles,omitempty"`
	Permissions   []string               `protobuf:"bytes,5,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserResponse) Reset() {
	*x = RegisterUserResponse{}
	mi := &file_api_proto_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserResponse) ProtoMessage() {}

func (x *RegisterUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserResponse.ProtoReflect.Descriptor instead.
func (*RegisterUserResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterUserResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RegisterUserResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterUserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterUserResponse) GetRoles() []UserRole {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *RegisterUserResponse) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

// Email Verification
type VerifyEmailRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VerificationToken string                 `protobuf:"bytes,2,opt,name=verification_token,json=verificationToken,proto3" json:"verification_token,omitempty"` // Token sent via email
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VerifyEmailRequest) Reset() {
	*x = VerifyEmailRequest{}
	mi := &file_api_proto_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyEmailRequest) ProtoMessage() {}

func (x *VerifyEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyEmailRequest.ProtoReflect.Descriptor instead.
func (*VerifyEmailRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyEmailRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *VerifyEmailRequest) GetVerificationToken() string {
	if x != nil {
		return x.VerificationToken
	}
	return ""
}

type VerifyEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyEmailResponse) Reset() {
	*x = VerifyEmailResponse{}
	mi := &file_api_proto_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyEmailResponse) ProtoMessage() {}

func (x *VerifyEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyEmailResponse.ProtoReflect.Descriptor instead.
func (*VerifyEmailResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyEmailResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Password Reset (forgot/reset)
type ForgotPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgotPasswordRequest) Reset() {
	*x = ForgotPasswordRequest{}
	mi := &file_api_proto_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgotPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgotPasswordRequest) ProtoMessage() {}

func (x *ForgotPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgotPasswordRequest.ProtoReflect.Descriptor instead.
func (*ForgotPasswordRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_proto_rawDescGZIP(), []int{4}
}

func (x *ForgotPasswordRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ForgotPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgotPasswordResponse) Reset() {
	*x = ForgotPasswordResponse{}
	mi := &file_api_proto_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgotPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgotPasswordResponse) ProtoMessage() {}

func (x *ForgotPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgotPasswordResponse.ProtoReflect.Descriptor instead.
func (*ForgotPasswordResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_proto_rawDescGZIP(), []int{5}
}

func (x *ForgotPasswordResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ResetPasswordByTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	NewPassword   string                 `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordByTokenRequest) Reset() {
	*x = ResetPasswordByTokenRequest{}
	mi := &file_api_proto_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordByTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordByTokenRequest) ProtoMessage() {}

func (x *ResetPasswordByTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordByTokenRequest.ProtoReflect.Descriptor instead.
func (*ResetPasswordByTokenRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_proto_rawDescGZIP(), []int{6}
}

func (x *ResetPasswordByTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ResetPasswordByTokenRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type ResetPasswordByTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordByTokenResponse) Reset() {
	*x = ResetPasswordByTokenResponse{}
	mi := &file_api_proto_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordByTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordByTokenResponse) ProtoMessage() {}

func (x *ResetPasswordByTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordByTokenResponse.ProtoReflect.Descriptor instead.
func (*ResetPasswordByTokenResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_proto_rawDescGZIP(), []int{7}
}

func (x *ResetPasswordByTokenResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Login / Logout
type UserLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"` // email or username
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	OrgId         string                 `protobuf:"bytes,4,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLoginRequest) Reset() {
	*x = UserLoginRequest{}
	mi := &file_api_proto_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginRequest) ProtoMessage() {}

func (x *UserLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginRequest.ProtoReflect.Descriptor instead.
func (*UserLoginRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_proto_rawDescGZIP(), []int{8}
}

func (x *UserLoginRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *UserLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserLoginRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UserLoginRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

type UserLoginResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Token            string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // JWT
	RefreshToken     string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	UserId           string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email            string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Name             string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Roles            []UserRole             `protobuf:"varint,6,rep,packed,name=roles,proto3,enum=UserRole" json:"roles,omitempty"`
	Permissions      []string               `protobuf:"bytes,7,rep,name=permissions,proto3" json:"permissions,omitempty"`
	LastLoginAt      string                 `protobuf:"bytes,8,opt,name=last_login_at,json=lastLoginAt,proto3" json:"last_login_at,omitempty"`
	LastLoginIp      string                 `protobuf:"bytes,9,opt,name=last_login_ip,json=lastLoginIp,proto3" json:"last_login_ip,omitempty"`
	TenantId         string                 `protobuf:"bytes,10,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	OrgId            string                 `protobuf:"bytes,11,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	TokenExpiresAt   int64                  `protobuf:"varint,12,opt,name=token_expires_at,json=tokenExpiresAt,proto3" json:"token_expires_at,omitempty"`
	RefreshExpiresAt int64                  `protobuf:"varint,13,opt,name=refresh_expires_at,json=refreshExpiresAt,proto3" json:"refresh_expires_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UserLoginResponse) Reset() {
	*x = UserLoginResponse{}
	mi := &file_api_proto_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginResponse) ProtoMessage() {}

func (x *UserLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginResponse.ProtoReflect.Descriptor instead.
func (*UserLoginResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_proto_rawDescGZIP(), []int{9}
}

func (x *UserLoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *UserLoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *UserLoginResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserLoginResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserLoginResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserLoginResponse) GetRoles() []UserRole {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *UserLoginResponse) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *UserLoginResponse) GetLastLoginAt() string {
	if x != nil {
		return x.LastLoginAt
	}
	return ""
}

func (x *UserLoginResponse) GetLastLoginIp() string {
	if x != nil {
		return x.LastLoginIp
	}
	return ""
}

func (x *UserLoginResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UserLoginResponse) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *UserLoginResponse) GetTokenExpiresAt() int64 {
	if x != nil {
		return x.TokenExpiresAt
	}
	return 0
}

func (x *UserLoginResponse) GetRefreshExpiresAt() int64 {
	if x != nil {
		return x.RefreshExpiresAt
	}
	return 0
}

type UserLogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLogoutRequest) Reset() {
	*x = UserLogoutRequest{}
	mi := &file_api_proto_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLogoutRequest) ProtoMessage() {}

func (x *UserLogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLogoutRequest.ProtoReflect.Descriptor instead.
func (*UserLogoutRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_proto_rawDescGZIP(), []int{10}
}

func (x *UserLogoutRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserLogoutRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type UserLogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLogoutResponse) Reset() {
	*x = UserLogoutResponse{}
	mi := &file_api_proto_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLogoutResponse) ProtoMessage() {}

func (x *UserLogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLogoutResponse.ProtoReflect.Descriptor instead.
func (*UserLogoutResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_proto_rawDescGZIP(), []int{11}
}

func (x *UserLogoutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	OrgId         string                 `protobuf:"bytes,3,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_api_proto_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_proto_rawDescGZIP(), []int{12}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshTokenRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RefreshTokenRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

type RefreshTokenResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Token            string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	RefreshToken     string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	TokenExpiresAt   int64                  `protobuf:"varint,3,opt,name=token_expires_at,json=tokenExpiresAt,proto3" json:"token_expires_at,omitempty"`
	RefreshExpiresAt int64                  `protobuf:"varint,4,opt,name=refresh_expires_at,json=refreshExpiresAt,proto3" json:"refresh_expires_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_api_proto_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_proto_rawDescGZIP(), []int{13}
}

func (x *RefreshTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RefreshTokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshTokenResponse) GetTokenExpiresAt() int64 {
	if x != nil {
		return x.TokenExpiresAt
	}
	return 0
}

func (x *RefreshTokenResponse) GetRefreshExpiresAt() int64 {
	if x != nil {
		return x.RefreshExpiresAt
	}
	return 0
}

type InitiateSSORequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	OrgId         string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Provider      SSOProvider            `protobuf:"varint,3,opt,name=provider,proto3,enum=SSOProvider" json:"provider,omitempty"`
	RedirectUri   string                 `protobuf:"bytes,4,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	State         string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateSSORequest) Reset() {
	*x = InitiateSSORequest{}
	mi := &file_api_proto_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateSSORequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateSSORequest) ProtoMessage() {}

func (x *InitiateSSORequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateSSORequest.ProtoReflect.Descriptor instead.
func (*InitiateSSORequest) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_proto_rawDescGZIP(), []int{14}
}

func (x *InitiateSSORequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *InitiateSSORequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *InitiateSSORequest) GetProvider() SSOProvider {
	if x != nil {
		return x.Provider
	}
	return SSOProvider_SSO_PROVIDER_UNSPECIFIED
}

func (x *InitiateSSORequest) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

func (x *InitiateSSORequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type InitiateSSOResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthUrl       string                 `protobuf:"bytes,1,opt,name=auth_url,json=authUrl,proto3" json:"auth_url,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateSSOResponse) Reset() {
	*x = InitiateSSOResponse{}
	mi := &file_api_proto_auth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateSSOResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateSSOResponse) ProtoMessage() {}

func (x *InitiateSSOResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateSSOResponse.ProtoReflect.Descriptor instead.
func (*InitiateSSOResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_proto_rawDescGZIP(), []int{15}
}

func (x *InitiateSSOResponse) GetAuthUrl() string {
	if x != nil {
		return x.AuthUrl
	}
	return ""
}

func (x *InitiateSSOResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type CompleteSSORequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	OrgId         string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Provider      SSOProvider            `protobuf:"varint,3,opt,name=provider,proto3,enum=SSOProvider" json:"provider,omitempty"`
	Code          string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	State         string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	RedirectUri   string                 `protobuf:"bytes,6,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteSSORequest) Reset() {
	*x = CompleteSSORequest{}
	mi := &file_api_proto_auth_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteSSORequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteSSORequest) ProtoMessage() {}

func (x *CompleteSSORequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteSSORequest.ProtoReflect.Descriptor instead.
func (*CompleteSSORequest) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_proto_rawDescGZIP(), []int{16}
}

func (x *CompleteSSORequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CompleteSSORequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *CompleteSSORequest) GetProvider() SSOProvider {
	if x != nil {
		return x.Provider
	}
	return SSOProvider_SSO_PROVIDER_UNSPECIFIED
}

func (x *CompleteSSORequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CompleteSSORequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *CompleteSSORequest) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

type InitiateSSOLogoutRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	TenantId              string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	OrgId                 string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Provider              SSOProvider            `protobuf:"varint,3,opt,name=provider,proto3,enum=SSOProvider" json:"provider,omitempty"`
	IdTokenHint           string                 `protobuf:"bytes,4,opt,name=id_token_hint,json=idTokenHint,proto3" json:"id_token_hint,omitempty"`
	PostLogoutRedirectUri string                 `protobuf:"bytes,5,opt,name=post_logout_redirect_uri,json=postLogoutRedirectUri,proto3" json:"post_logout_redirect_uri,omitempty"`
	State                 string                 `protobuf:"bytes,6,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *InitiateSSOLogoutRequest) Reset() {
	*x = InitiateSSOLogoutRequest{}
	mi := &file_api_proto_auth_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateSSOLogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateSSOLogoutRequest) ProtoMessage() {}

func (x *InitiateSSOLogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateSSOLogoutRequest.ProtoReflect.Descriptor instead.
func (*InitiateSSOLogoutRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_proto_rawDescGZIP(), []int{17}
}

func (x *InitiateSSOLogoutRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *InitiateSSOLogoutRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *InitiateSSOLogoutRequest) GetProvider() SSOProvider {
	if x != nil {
		return x.Provider
	}
	return SSOProvider_SSO_PROVIDER_UNSPECIFIED
}

func (x *InitiateSSOLogoutRequest) GetIdTokenHint() string {
	if x != nil {
		return x.IdTokenHint
	}
	return ""
}

func (x *InitiateSSOLogoutRequest) GetPostLogoutRedirectUri() string {
	if x != nil {
		return x.PostLogoutRedirectUri
	}
	return ""
}

func (x *InitiateSSOLogoutRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type InitiateSSOLogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogoutUrl     string                 `protobuf:"bytes,1,opt,name=logout_url,json=logoutUrl,proto3" json:"logout_url,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateSSOLogoutResponse) Reset() {
	*x = InitiateSSOLogoutResponse{}
	mi := &file_api_proto_auth_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateSSOLogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateSSOLogoutResponse) ProtoMessage() {}

func (x *InitiateSSOLogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateSSOLogoutResponse.ProtoReflect.Descriptor instead.
func (*InitiateSSOLogoutResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_proto_rawDescGZIP(), []int{18}
}

func (x *InitiateSSOLogoutResponse) GetLogoutUrl() string {
	if x != nil {
		return x.LogoutUrl
	}
	return ""
}

func (x *InitiateSSOLogoutResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type CompleteSSOLogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	OrgId         string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Provider      SSOProvider            `protobuf:"varint,3,opt,name=provider,proto3,enum=SSOProvider" json:"provider,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteSSOLogoutRequest) Reset() {
	*x = CompleteSSOLogoutRequest{}
	mi := &file_api_proto_auth_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteSSOLogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteSSOLogoutRequest) ProtoMessage() {}

func (x *CompleteSSOLogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteSSOLogoutRequest.ProtoReflect.Descriptor instead.
func (*CompleteSSOLogoutRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_proto_rawDescGZIP(), []int{19}
}

func (x *CompleteSSOLogoutRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CompleteSSOLogoutRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *CompleteSSOLogoutRequest) GetProvider() SSOProvider {
	if x != nil {
		return x.Provider
	}
	return SSOProvider_SSO_PROVIDER_UNSPECIFIED
}

func (x *CompleteSSOLogoutRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type SendVerificationEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendVerificationEmailRequest) Reset() {
	*x = SendVerificationEmailRequest{}
	mi := &file_api_proto_auth_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendVerificationEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendVerificationEmailRequest) ProtoMessage() {}

func (x *SendVerificationEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendVerificationEmailRequest.ProtoReflect.Descriptor instead.
func (*SendVerificationEmailRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_proto_rawDescGZIP(), []int{20}
}

func (x *SendVerificationEmailRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type SendVerificationEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendVerificationEmailResponse) Reset() {
	*x = SendVerificationEmailResponse{}
	mi := &file_api_proto_auth_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendVerificationEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendVerificationEmailResponse) ProtoMessage() {}

func (x *SendVerificationEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendVerificationEmailResponse.ProtoReflect.Descriptor instead.
func (*SendVerificationEmailResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_proto_rawDescGZIP(), []int{21}
}

func (x *SendVerificationEmailResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SendPasswordResetEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPasswordResetEmailRequest) Reset() {
	*x = SendPasswordResetEmailRequest{}
	mi := &file_api_proto_auth_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPasswordResetEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPasswordResetEmailRequest) ProtoMessage() {}

func (x *SendPasswordResetEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPasswordResetEmailRequest.ProtoReflect.Descriptor instead.
func (*SendPasswordResetEmailRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_proto_rawDescGZIP(), []int{22}
}

func (x *SendPasswordResetEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type SendPasswordResetEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPasswordResetEmailResponse) Reset() {
	*x = SendPasswordResetEmailResponse{}
	mi := &file_api_proto_auth_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPasswordResetEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPasswordResetEmailResponse) ProtoMessage() {}

func (x *SendPasswordResetEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPasswordResetEmailResponse.ProtoReflect.Descriptor instead.
func (*SendPasswordResetEmailResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_proto_rawDescGZIP(), []int{23}
}

func (x *SendPasswordResetEmailResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_proto_auth_proto protoreflect.FileDescriptor

const file_api_proto_auth_proto_rawDesc = "" +
	"\n" +
	"\x14api/proto/auth.proto\x1a\x1cgoogle/api/annotations.proto\"\x99\x01\n" +
	"\x13RegisterUserRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x1f\n" +
	"\x05roles\x18\x05 \x03(\x0e2\t.UserRoleR\x05roles\"\x9c\x01\n" +
	"\x14RegisterUserResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1f\n" +
	"\x05roles\x18\x04 \x03(\x0e2\t.UserRoleR\x05roles\x12 \n" +
	"\vpermissions\x18\x05 \x03(\tR\vpermissions\"\\\n" +
	"\x12VerifyEmailRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12-\n" +
	"\x12verification_token\x18\x02 \x01(\tR\x11verificationToken\"/\n" +
	"\x13VerifyEmailResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"-\n" +
	"\x15ForgotPasswordRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"2\n" +
	"\x16ForgotPasswordResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"V\n" +
	"\x1bResetPasswordByTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12!\n" +
	"\fnew_password\x18\x02 \x01(\tR\vnewPassword\"8\n" +
	"\x1cResetPasswordByTokenResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"x\n" +
	"\x10UserLoginRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12\x15\n" +
	"\x06org_id\x18\x04 \x01(\tR\x05orgId\"\xa8\x03\n" +
	"\x11UserLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x1f\n" +
	"\x05roles\x18\x06 \x03(\x0e2\t.UserRoleR\x05roles\x12 \n" +
	"\vpermissions\x18\a \x03(\tR\vpermissions\x12\"\n" +
	"\rlast_login_at\x18\b \x01(\tR\vlastLoginAt\x12\"\n" +
	"\rlast_login_ip\x18\t \x01(\tR\vlastLoginIp\x12\x1b\n" +
	"\ttenant_id\x18\n" +
	" \x01(\tR\btenantId\x12\x15\n" +
	"\x06org_id\x18\v \x01(\tR\x05orgId\x12(\n" +
	"\x10token_expires_at\x18\f \x01(\x03R\x0etokenExpiresAt\x12,\n" +
	"\x12refresh_expires_at\x18\r \x01(\x03R\x10refreshExpiresAt\"Q\n" +
	"\x11UserLogoutRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\".\n" +
	"\x12UserLogoutResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"n\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x15\n" +
	"\x06org_id\x18\x03 \x01(\tR\x05orgId\"\xa9\x01\n" +
	"\x14RefreshTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12(\n" +
	"\x10token_expires_at\x18\x03 \x01(\x03R\x0etokenExpiresAt\x12,\n" +
	"\x12refresh_expires_at\x18\x04 \x01(\x03R\x10refreshExpiresAt\"\xab\x01\n" +
	"\x12InitiateSSORequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\x12(\n" +
	"\bprovider\x18\x03 \x01(\x0e2\f.SSOProviderR\bprovider\x12!\n" +
	"\fredirect_uri\x18\x04 \x01(\tR\vredirectUri\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\"F\n" +
	"\x13InitiateSSOResponse\x12\x19\n" +
	"\bauth_url\x18\x01 \x01(\tR\aauthUrl\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\"\xbf\x01\n" +
	"\x12CompleteSSORequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\x12(\n" +
	"\bprovider\x18\x03 \x01(\x0e2\f.SSOProviderR\bprovider\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12!\n" +
	"\fredirect_uri\x18\x06 \x01(\tR\vredirectUri\"\xeb\x01\n" +
	"\x18InitiateSSOLogoutRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\x12(\n" +
	"\bprovider\x18\x03 \x01(\x0e2\f.SSOProviderR\bprovider\x12\"\n" +
	"\rid_token_hint\x18\x04 \x01(\tR\vidTokenHint\x127\n" +
	"\x18post_logout_redirect_uri\x18\x05 \x01(\tR\x15postLogoutRedirectUri\x12\x14\n" +
	"\x05state\x18\x06 \x01(\tR\x05state\"P\n" +
	"\x19InitiateSSOLogoutResponse\x12\x1d\n" +
	"\n" +
	"logout_url\x18\x01 \x01(\tR\tlogoutUrl\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\"\x8e\x01\n" +
	"\x18CompleteSSOLogoutRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\x12(\n" +
	"\bprovider\x18\x03 \x01(\x0e2\f.SSOProviderR\bprovider\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\"7\n" +
	"\x1cSendVerificationEmailRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"9\n" +
	"\x1dSendVerificationEmailResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"5\n" +
	"\x1dSendPasswordResetEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\":\n" +
	"\x1eSendPasswordResetEmailResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*A\n" +
	"\bUserRole\x12\x19\n" +
	"\x15USER_ROLE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vSUPER_ADMIN\x10\x01\x12\t\n" +
	"\x05ADMIN\x10\x02*o\n" +
	"\vSSOProvider\x12\x1c\n" +
	"\x18SSO_PROVIDER_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06GOOGLE\x10\x01\x12\r\n" +
	"\tMICROSOFT\x10\x02\x12\b\n" +
	"\x04OKTA\x10\x03\x12\f\n" +
	"\bKEYCLOAK\x10\x04\x12\x0f\n" +
	"\vCUSTOM_OIDC\x10\x052\xe8\n" +
	"\n" +
	"\vAuthService\x12]\n" +
	"\fRegisterUser\x12\x14.RegisterUserRequest\x1a\x15.RegisterUserResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/v1/auth/register\x12^\n" +
	"\vVerifyEmail\x12\x13.VerifyEmailRequest\x1a\x14.VerifyEmailResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/api/v1/auth/verify-email\x12j\n" +
	"\x0eForgotPassword\x12\x16.ForgotPasswordRequest\x1a\x17.ForgotPasswordResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/api/v1/auth/forgot-password\x12{\n" +
	"\x14ResetPasswordByToken\x12\x1c.ResetPasswordByTokenRequest\x1a\x1d.ResetPasswordByTokenResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/api/v1/auth/reset-password\x12M\n" +
	"\x05Login\x12\x11.UserLoginRequest\x1a\x12.UserLoginResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/v1/auth/login\x12Q\n" +
	"\x06Logout\x12\x12.UserLogoutRequest\x1a\x13.UserLogoutResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/auth/logout\x12\\\n" +
	"\fRefreshToken\x12\x14.RefreshTokenRequest\x1a\x15.RefreshTokenResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/auth/refresh\x12^\n" +
	"\vInitiateSSO\x12\x13.InitiateSSORequest\x1a\x14.InitiateSSOResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/api/v1/auth/sso/initiate\x12\\\n" +
	"\vCompleteSSO\x12\x13.CompleteSSORequest\x1a\x12.UserLoginResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/api/v1/auth/sso/complete\x12w\n" +
	"\x11InitiateSSOLogout\x12\x19.InitiateSSOLogoutRequest\x1a\x1a.InitiateSSOLogoutResponse\"+\x82\xd3\xe4\x93\x02%:\x01*\" /api/v1/auth/sso/logout/initiate\x12p\n" +
	"\x11CompleteSSOLogout\x12\x19.CompleteSSOLogoutRequest\x1a\x13.UserLogoutResponse\"+\x82\xd3\xe4\x93\x02%:\x01*\" /api/v1/auth/sso/logout/complete\x12\x81\x01\n" +
	"\x15SendVerificationEmail\x12\x1d.SendVerificationEmailRequest\x1a\x1e.SendVerificationEmailResponse\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/api/v1/auth/send-verification\x12\x83\x01\n" +
	"\x16SendPasswordResetEmail\x12\x1e.SendPasswordResetEmailRequest\x1a\x1f.SendPasswordResetEmailResponse\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/api/v1/auth/send-reset-emailB2Z0github.com/ShristiRnr/NHIT_Backend/api/pb/authpbb\x06proto3"

var (
	file_api_proto_auth_proto_rawDescOnce sync.Once
	file_api_proto_auth_proto_rawDescData []byte
)

func file_api_proto_auth_proto_rawDescGZIP() []byte {
	file_api_proto_auth_proto_rawDescOnce.Do(func() {
		file_api_proto_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_auth_proto_rawDesc), len(file_api_proto_auth_proto_rawDesc)))
	})
	return file_api_proto_auth_proto_rawDescData
}

var file_api_proto_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_api_proto_auth_proto_goTypes = []any{
	(UserRole)(0),                          // 0: UserRole
	(SSOProvider)(0),                       // 1: SSOProvider
	(*RegisterUserRequest)(nil),            // 2: RegisterUserRequest
	(*RegisterUserResponse)(nil),           // 3: RegisterUserResponse
	(*VerifyEmailRequest)(nil),             // 4: VerifyEmailRequest
	(*VerifyEmailResponse)(nil),            // 5: VerifyEmailResponse
	(*ForgotPasswordRequest)(nil),          // 6: ForgotPasswordRequest
	(*ForgotPasswordResponse)(nil),         // 7: ForgotPasswordResponse
	(*ResetPasswordByTokenRequest)(nil),    // 8: ResetPasswordByTokenRequest
	(*ResetPasswordByTokenResponse)(nil),   // 9: ResetPasswordByTokenResponse
	(*UserLoginRequest)(nil),               // 10: UserLoginRequest
	(*UserLoginResponse)(nil),              // 11: UserLoginResponse
	(*UserLogoutRequest)(nil),              // 12: UserLogoutRequest
	(*UserLogoutResponse)(nil),             // 13: UserLogoutResponse
	(*RefreshTokenRequest)(nil),            // 14: RefreshTokenRequest
	(*RefreshTokenResponse)(nil),           // 15: RefreshTokenResponse
	(*InitiateSSORequest)(nil),             // 16: InitiateSSORequest
	(*InitiateSSOResponse)(nil),            // 17: InitiateSSOResponse
	(*CompleteSSORequest)(nil),             // 18: CompleteSSORequest
	(*InitiateSSOLogoutRequest)(nil),       // 19: InitiateSSOLogoutRequest
	(*InitiateSSOLogoutResponse)(nil),      // 20: InitiateSSOLogoutResponse
	(*CompleteSSOLogoutRequest)(nil),       // 21: CompleteSSOLogoutRequest
	(*SendVerificationEmailRequest)(nil),   // 22: SendVerificationEmailRequest
	(*SendVerificationEmailResponse)(nil),  // 23: SendVerificationEmailResponse
	(*SendPasswordResetEmailRequest)(nil),  // 24: SendPasswordResetEmailRequest
	(*SendPasswordResetEmailResponse)(nil), // 25: SendPasswordResetEmailResponse
}
var file_api_proto_auth_proto_depIdxs = []int32{
	0,  // 0: RegisterUserRequest.roles:type_name -> UserRole
	0,  // 1: RegisterUserResponse.roles:type_name -> UserRole
	0,  // 2: UserLoginResponse.roles:type_name -> UserRole
	1,  // 3: InitiateSSORequest.provider:type_name -> SSOProvider
	1,  // 4: CompleteSSORequest.provider:type_name -> SSOProvider
	1,  // 5: InitiateSSOLogoutRequest.provider:type_name -> SSOProvider
	1,  // 6: CompleteSSOLogoutRequest.provider:type_name -> SSOProvider
	2,  // 7: AuthService.RegisterUser:input_type -> RegisterUserRequest
	4,  // 8: AuthService.VerifyEmail:input_type -> VerifyEmailRequest
	6,  // 9: AuthService.ForgotPassword:input_type -> ForgotPasswordRequest
	8,  // 10: AuthService.ResetPasswordByToken:input_type -> ResetPasswordByTokenRequest
	10, // 11: AuthService.Login:input_type -> UserLoginRequest
	12, // 12: AuthService.Logout:input_type -> UserLogoutRequest
	14, // 13: AuthService.RefreshToken:input_type -> RefreshTokenRequest
	16, // 14: AuthService.InitiateSSO:input_type -> InitiateSSORequest
	18, // 15: AuthService.CompleteSSO:input_type -> CompleteSSORequest
	19, // 16: AuthService.InitiateSSOLogout:input_type -> InitiateSSOLogoutRequest
	21, // 17: AuthService.CompleteSSOLogout:input_type -> CompleteSSOLogoutRequest
	22, // 18: AuthService.SendVerificationEmail:input_type -> SendVerificationEmailRequest
	24, // 19: AuthService.SendPasswordResetEmail:input_type -> SendPasswordResetEmailRequest
	3,  // 20: AuthService.RegisterUser:output_type -> RegisterUserResponse
	5,  // 21: AuthService.VerifyEmail:output_type -> VerifyEmailResponse
	7,  // 22: AuthService.ForgotPassword:output_type -> ForgotPasswordResponse
	9,  // 23: AuthService.ResetPasswordByToken:output_type -> ResetPasswordByTokenResponse
	11, // 24: AuthService.Login:output_type -> UserLoginResponse
	13, // 25: AuthService.Logout:output_type -> UserLogoutResponse
	15, // 26: AuthService.RefreshToken:output_type -> RefreshTokenResponse
	17, // 27: AuthService.InitiateSSO:output_type -> InitiateSSOResponse
	11, // 28: AuthService.CompleteSSO:output_type -> UserLoginResponse
	20, // 29: AuthService.InitiateSSOLogout:output_type -> InitiateSSOLogoutResponse
	13, // 30: AuthService.CompleteSSOLogout:output_type -> UserLogoutResponse
	23, // 31: AuthService.SendVerificationEmail:output_type -> SendVerificationEmailResponse
	25, // 32: AuthService.SendPasswordResetEmail:output_type -> SendPasswordResetEmailResponse
	20, // [20:33] is the sub-list for method output_type
	7,  // [7:20] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_proto_auth_proto_init() }
func file_api_proto_auth_proto_init() {
	if File_api_proto_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_auth_proto_rawDesc), len(file_api_proto_auth_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_auth_proto_goTypes,
		DependencyIndexes: file_api_proto_auth_proto_depIdxs,
		EnumInfos:         file_api_proto_auth_proto_enumTypes,
		MessageInfos:      file_api_proto_auth_proto_msgTypes,
	}.Build()
	File_api_proto_auth_proto = out.File
	file_api_proto_auth_proto_goTypes = nil
	file_api_proto_auth_proto_depIdxs = nil
}
