// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type EmailVerificationToken struct {
	Token     uuid.UUID
	UserID    uuid.UUID
	ExpiresAt time.Time
	CreatedAt sql.NullTime
}

type Organization struct {
	OrgID     uuid.UUID
	TenantID  uuid.UUID
	Name      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type PasswordReset struct {
	Token     uuid.UUID
	UserID    uuid.UUID
	ExpiresAt time.Time
	CreatedAt sql.NullTime
}

type Permission struct {
	PermissionID uuid.UUID
	Name         string
	Description  sql.NullString
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

type RefreshToken struct {
	Token     string
	UserID    uuid.NullUUID
	ExpiresAt time.Time
	CreatedAt sql.NullTime
}

type Role struct {
	RoleID    uuid.UUID
	TenantID  uuid.UUID
	Name      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type RolePermission struct {
	RoleID       uuid.UUID
	PermissionID uuid.UUID
}

type Session struct {
	SessionID    uuid.UUID
	UserID       uuid.NullUUID
	SessionToken string
	CreatedAt    sql.NullTime
	ExpiresAt    sql.NullTime
}

type Tenant struct {
	TenantID         uuid.UUID
	Name             string
	SuperAdminUserID uuid.NullUUID
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
}

type User struct {
	UserID          uuid.UUID
	TenantID        uuid.UUID
	Name            string
	Email           string
	Password        string
	EmailVerifiedAt sql.NullTime
	LastLoginAt     sql.NullTime
	LastLogoutAt    sql.NullTime
	LastLoginIp     sql.NullString
	UserAgent       sql.NullString
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
}

type UserLoginHistory struct {
	HistoryID uuid.UUID
	UserID    uuid.NullUUID
	IpAddress sql.NullString
	UserAgent sql.NullString
	LoginTime sql.NullTime
}

type UserOrganization struct {
	UserID uuid.UUID
	OrgID  uuid.UUID
	RoleID uuid.UUID
}

type UserRole struct {
	UserID uuid.UUID
	RoleID uuid.UUID
}
