// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_roles.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const assignRoleToUser = `-- name: AssignRoleToUser :exec
INSERT INTO user_roles (user_id, role_id)
VALUES ($1, $2)
ON CONFLICT (user_id, role_id) DO NOTHING
`

type AssignRoleToUserParams struct {
	UserID uuid.UUID
	RoleID uuid.UUID
}

func (q *Queries) AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) error {
	_, err := q.db.ExecContext(ctx, assignRoleToUser, arg.UserID, arg.RoleID)
	return err
}

const listRolesForUser = `-- name: ListRolesForUser :many
SELECT r.role_id, r.name
FROM roles r
JOIN user_roles ur ON r.role_id = ur.role_id
WHERE ur.user_id = $1
`

type ListRolesForUserRow struct {
	RoleID uuid.UUID
	Name   string
}

func (q *Queries) ListRolesForUser(ctx context.Context, userID uuid.UUID) ([]ListRolesForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listRolesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRolesForUserRow
	for rows.Next() {
		var i ListRolesForUserRow
		if err := rows.Scan(&i.RoleID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
