package domain

import (
	"fmt"
	"regexp"
	"strings"
	"time"

	"github.com/google/uuid"
)

// Vendor represents the vendor domain model with complete business logic
type Vendor struct {
	ID                      uuid.UUID  `json:"id" db:"id"`
	TenantID                uuid.UUID  `json:"tenant_id" db:"tenant_id"`
	VendorCode              string     `json:"vendor_code" db:"vendor_code"`
	VendorName              string     `json:"vendor_name" db:"vendor_name"`
	VendorEmail             string     `json:"vendor_email" db:"vendor_email"`
	VendorMobile            *string    `json:"vendor_mobile" db:"vendor_mobile"`
	AccountType             string     `json:"account_type" db:"account_type"`
	VendorNickName          *string    `json:"vendor_nick_name" db:"vendor_nick_name"`
	ActivityType            *string    `json:"activity_type" db:"activity_type"`
	Email                   *string    `json:"email" db:"email"`
	Mobile                  *string    `json:"mobile" db:"mobile"`
	GSTIN                   *string    `json:"gstin" db:"gstin"`
	PAN                     string     `json:"pan" db:"pan"`
	PIN                     *string    `json:"pin" db:"pin"`
	CountryName             *string    `json:"country_name" db:"country_name"`
	StateName               *string    `json:"state_name" db:"state_name"`
	CityName                *string    `json:"city_name" db:"city_name"`
	Address                 *string    `json:"address" db:"address"`
	MSMEClassification      string     `json:"msme_classification" db:"msme_classification"`
	MSME                    *string    `json:"msme" db:"msme"`
	MSMERegistrationNumber  *string    `json:"msme_registration_number" db:"msme_registration_number"`
	MSMEStartDate           *time.Time `json:"msme_start_date" db:"msme_start_date"`
	MSMEEndDate             *time.Time `json:"msme_end_date" db:"msme_end_date"`
	MaterialNature          *string    `json:"material_nature" db:"material_nature"`
	GSTDefaulted            *string    `json:"gst_defaulted" db:"gst_defaulted"`
	Section206ABVerified    *string    `json:"section_206ab_verified" db:"section_206ab_verified"`
	BeneficiaryName         string     `json:"beneficiary_name" db:"beneficiary_name"`
	RemarksAddress          *string    `json:"remarks_address" db:"remarks_address"`
	CommonBankDetails       *string    `json:"common_bank_details" db:"common_bank_details"`
	IncomeTaxType           *string    `json:"income_tax_type" db:"income_tax_type"`
	ProjectID               *string    `json:"project_id" db:"project_id"`
	Status                  string     `json:"status" db:"status"`
	FromAccountType         *string    `json:"from_account_type" db:"from_account_type"`
	AccountName             *string    `json:"account_name" db:"account_name"`
	ShortName               *string    `json:"short_name" db:"short_name"`
	Parent                  *string    `json:"parent" db:"parent"`
	FilePaths               []string   `json:"file_paths" db:"file_paths"`
	CodeAutoGenerated       bool       `json:"code_auto_generated" db:"code_auto_generated"`
	CreatedBy               uuid.UUID  `json:"created_by" db:"created_by"`
	CreatedAt               time.Time  `json:"created_at" db:"created_at"`
	UpdatedAt               time.Time  `json:"updated_at" db:"updated_at"`
	
	// Banking details (for backward compatibility)
	AccountNumber           *string    `json:"account_number" db:"account_number"`
	NameOfBank              *string    `json:"name_of_bank" db:"name_of_bank"`
	IFSCCode                *string    `json:"ifsc_code" db:"ifsc_code"`
	SignatureURL            *string    `json:"signature_url" db:"signature_url"`
}

// VendorAccount represents the vendor account domain model
type VendorAccount struct {
	ID            uuid.UUID  `json:"id" db:"id"`
	VendorID      uuid.UUID  `json:"vendor_id" db:"vendor_id"`
	AccountName   string     `json:"account_name" db:"account_name"`
	AccountNumber string     `json:"account_number" db:"account_number"`
	AccountType   *string    `json:"account_type" db:"account_type"`
	NameOfBank    string     `json:"name_of_bank" db:"name_of_bank"`
	BranchName    *string    `json:"branch_name" db:"branch_name"`
	IFSCCode      string     `json:"ifsc_code" db:"ifsc_code"`
	SwiftCode     *string    `json:"swift_code" db:"swift_code"`
	IsPrimary     bool       `json:"is_primary" db:"is_primary"`
	IsActive      bool       `json:"is_active" db:"is_active"`
	Remarks       *string    `json:"remarks" db:"remarks"`
	CreatedBy     uuid.UUID  `json:"created_by" db:"created_by"`
	CreatedAt     time.Time  `json:"created_at" db:"created_at"`
	UpdatedAt     time.Time  `json:"updated_at" db:"updated_at"`
}

// NewVendor creates a new vendor with business validation
func NewVendor(params CreateVendorParams) (*Vendor, error) {
	if err := params.Validate(); err != nil {
		return nil, err
	}

	vendor := &Vendor{
		ID:                uuid.New(),
		TenantID:          params.TenantID,
		VendorName:        params.VendorName,
		VendorEmail:       params.VendorEmail,
		VendorMobile:      params.VendorMobile,
		AccountType:       params.AccountType,
		VendorNickName:    params.VendorNickName,
		ActivityType:      params.ActivityType,
		Email:             params.Email,
		Mobile:            params.Mobile,
		GSTIN:             params.GSTIN,
		PAN:               params.PAN,
		PIN:               params.PIN,
		CountryName:       params.CountryName,
		StateName:         params.StateName,
		CityName:          params.CityName,
		Address:           params.Address,
		MSMEClassification: params.MSMEClassification,
		MSME:              params.MSME,
		MSMERegistrationNumber: params.MSMERegistrationNumber,
		MSMEStartDate:     params.MSMEStartDate,
		MSMEEndDate:       params.MSMEEndDate,
		MaterialNature:    params.MaterialNature,
		GSTDefaulted:      params.GSTDefaulted,
		Section206ABVerified: params.Section206ABVerified,
		BeneficiaryName:   params.BeneficiaryName,
		RemarksAddress:    params.RemarksAddress,
		CommonBankDetails: params.CommonBankDetails,
		IncomeTaxType:     params.IncomeTaxType,
		ProjectID:         params.ProjectID,
		Status:            params.Status,
		FromAccountType:   params.FromAccountType,
		AccountName:       params.AccountName,
		ShortName:         params.ShortName,
		Parent:            params.Parent,
		FilePaths:         params.FilePaths,
		AccountNumber:     params.AccountNumber,
		NameOfBank:        params.NameOfBank,
		IFSCCode:          params.IFSCCode,
		SignatureURL:      params.SignatureURL,
		CodeAutoGenerated: true,
		CreatedBy:         params.CreatedBy,
		CreatedAt:         time.Now(),
		UpdatedAt:         time.Now(),
	}

	// Generate vendor code
	vendor.VendorCode = vendor.GenerateCode()
	return vendor, nil
}

// CreateVendorParams holds parameters for creating a vendor
type CreateVendorParams struct {
	TenantID                uuid.UUID
	VendorName              string
	VendorEmail             string
	VendorMobile            *string
	AccountType             string
	VendorNickName          *string
	ActivityType            *string
	Email                   *string
	Mobile                  *string
	GSTIN                   *string
	PAN                     string
	PIN                     *string
	CountryName             *string
	StateName               *string
	CityName                *string
	Address                 *string
	MSMEClassification      string
	MSME                    *string
	MSMERegistrationNumber  *string
	MSMEStartDate           *time.Time
	MSMEEndDate             *time.Time
	MaterialNature          *string
	GSTDefaulted            *string
	Section206ABVerified    *string
	BeneficiaryName         string
	RemarksAddress          *string
	CommonBankDetails       *string
	IncomeTaxType           *string
	ProjectID               *string
	Status                  string
	FromAccountType         *string
	AccountName             *string
	ShortName               *string
	Parent                  *string
	FilePaths               []string
	AccountNumber           *string
	NameOfBank              *string
	IFSCCode                *string
	SignatureURL            *string
	CreatedBy               uuid.UUID
}

// Validate validates the create vendor parameters
func (p CreateVendorParams) Validate() error {
	if p.TenantID == uuid.Nil {
		return ErrInvalidTenantID
	}
	if p.VendorName == "" {
		return ErrInvalidVendorName
	}
	if p.VendorEmail == "" {
		return ErrInvalidVendorEmail
	}
	if !isValidEmail(p.VendorEmail) {
		return ErrInvalidEmailFormat
	}
	if p.PAN == "" {
		return ErrInvalidPAN
	}
	if !isValidPAN(p.PAN) {
		return ErrInvalidPANFormat
	}
	if p.BeneficiaryName == "" {
		return ErrInvalidBeneficiaryName
	}
	if p.CreatedBy == uuid.Nil {
		return ErrInvalidCreatedBy
	}
	if p.IFSCCode != nil && !isValidIFSC(*p.IFSCCode) {
		return ErrInvalidIFSCFormat
	}
	return nil
}

// GenerateCode generates vendor code based on name and type
func (v *Vendor) GenerateCode() string {
	name := strings.TrimSpace(v.VendorName)
	name = regexp.MustCompile(`[^a-zA-Z0-9\s]`).ReplaceAllString(name, "")
	words := strings.Fields(name)
	
	var prefix string
	if len(words) > 0 {
		if len(words[0]) >= 3 {
			prefix = strings.ToUpper(words[0][:3])
		} else {
			prefix = strings.ToUpper(words[0])
		}
	} else {
		prefix = "VEN"
	}

	typePrefix := "EXT"  // Default to EXTERNAL
	if strings.ToUpper(v.AccountType) == "INTERNAL" {
		typePrefix = "INT"
	}

	timestamp := time.Now().Format("060102")
	return fmt.Sprintf("%s-%s-%s", typePrefix, prefix, timestamp)
}

// UpdateCode updates vendor code
func (v *Vendor) UpdateCode(newCode string) error {
	if newCode == "" {
		return ErrInvalidVendorCode
	}
	v.VendorCode = newCode
	v.CodeAutoGenerated = false
	v.UpdatedAt = time.Now()
	return nil
}

// RegenerateCode regenerates vendor code
func (v *Vendor) RegenerateCode() {
	v.VendorCode = v.GenerateCode()
	v.CodeAutoGenerated = true
	v.UpdatedAt = time.Now()
}

// Update updates vendor fields
func (v *Vendor) Update(updates UpdateVendorParams) error {
	if err := updates.Validate(); err != nil {
		return err
	}

	if updates.VendorName != nil {
		v.VendorName = *updates.VendorName
	}
	if updates.VendorEmail != nil {
		v.VendorEmail = *updates.VendorEmail
	}
	if updates.PAN != nil {
		v.PAN = *updates.PAN
	}
	if updates.BeneficiaryName != nil {
		v.BeneficiaryName = *updates.BeneficiaryName
	}
	if updates.Status != nil {
		v.Status = *updates.Status
	}
	if updates.MSMEClassification != nil {
		v.MSMEClassification = *updates.MSMEClassification
	}
	if updates.MSME != nil {
		v.MSME = updates.MSME
	}
	if updates.MSMERegistrationNumber != nil {
		v.MSMERegistrationNumber = updates.MSMERegistrationNumber
	}
	if updates.MSMEStartDate != nil {
		v.MSMEStartDate = updates.MSMEStartDate
	}
	if updates.MSMEEndDate != nil {
		v.MSMEEndDate = updates.MSMEEndDate
	}
	if updates.MaterialNature != nil {
		v.MaterialNature = updates.MaterialNature
	}
	if updates.GSTDefaulted != nil {
		v.GSTDefaulted = updates.GSTDefaulted
	}
	if updates.Section206ABVerified != nil {
		v.Section206ABVerified = updates.Section206ABVerified
	}
	if updates.IncomeTaxType != nil {
		v.IncomeTaxType = updates.IncomeTaxType
	}
	if updates.ProjectID != nil {
		v.ProjectID = updates.ProjectID
	}
	if updates.AccountName != nil {
		v.AccountName = updates.AccountName
	}
	if updates.AccountType != nil {
		v.AccountType = *updates.AccountType
	}
	if updates.RemarksAddress != nil {
		v.RemarksAddress = updates.RemarksAddress
	}
	if updates.Address != nil {
		v.Address = updates.Address
	}
	if updates.PIN != nil {
		v.PIN = updates.PIN
	}
	if updates.ActivityType != nil {
		v.ActivityType = updates.ActivityType
	}
	if updates.VendorNickName != nil {
		v.VendorNickName = updates.VendorNickName
	}
	if updates.CountryName != nil {
		v.CountryName = updates.CountryName
	}
	if updates.StateName != nil {
		v.StateName = updates.StateName
	}
	if updates.CityName != nil {
		v.CityName = updates.CityName
	}
	if updates.FromAccountType != nil {
		v.FromAccountType = updates.FromAccountType
	}
	if updates.ShortName != nil {
		v.ShortName = updates.ShortName
	}
	if updates.Parent != nil {
		v.Parent = updates.Parent
	}
	if updates.SignatureURL != nil {
		v.SignatureURL = updates.SignatureURL
	}

	v.UpdatedAt = time.Now()
	return nil
}

// UpdateVendorParams holds parameters for updating a vendor
type UpdateVendorParams struct {
	VendorName             *string
	VendorEmail            *string
	VendorMobile           *string
	PAN                    *string
	BeneficiaryName        *string
	Status                 *string
	MSMEClassification     *string
	MSME                   *string
	MSMERegistrationNumber *string
	MSMEStartDate          *time.Time
	MSMEEndDate            *time.Time
	MaterialNature         *string
	GSTDefaulted           *string
	Section206ABVerified   *string
	IncomeTaxType          *string
	ProjectID              *string
	AccountName            *string
	AccountType            *string
	RemarksAddress         *string
	ReviewStatus           *string
	Address                *string
	PIN                    *string
	ActivityType           *string
	VendorNickName         *string
	CountryName            *string
	StateName              *string
	CityName               *string
	FromAccountType        *string
	ShortName              *string
	Parent                 *string
	SignatureURL           *string
}

// Validate validates update parameters
func (p UpdateVendorParams) Validate() error {
	if p.VendorEmail != nil && !isValidEmail(*p.VendorEmail) {
		return ErrInvalidEmailFormat
	}
	if p.PAN != nil && !isValidPAN(*p.PAN) {
		return ErrInvalidPANFormat
	}
	return nil
}

// NewVendorAccount creates a new vendor account
func NewVendorAccount(params CreateVendorAccountParams) (*VendorAccount, error) {
	if err := params.Validate(); err != nil {
		return nil, err
	}

	return &VendorAccount{
		ID:            uuid.New(),
		VendorID:      params.VendorID,
		AccountName:   params.AccountName,
		AccountNumber: params.AccountNumber,
		AccountType:   params.AccountType,
		NameOfBank:    params.NameOfBank,
		BranchName:    params.BranchName,
		IFSCCode:      params.IFSCCode,
		SwiftCode:     params.SwiftCode,
		IsPrimary:     params.IsPrimary,
		IsActive:      true,
		Remarks:       params.Remarks,
		CreatedBy:     params.CreatedBy,
		CreatedAt:     time.Now(),
		UpdatedAt:     time.Now(),
	}, nil
}

// CreateVendorAccountParams holds parameters for creating vendor account
type CreateVendorAccountParams struct {
	VendorID      uuid.UUID
	AccountName   string
	AccountNumber string
	AccountType   *string
	NameOfBank    string
	BranchName    *string
	IFSCCode      string
	SwiftCode     *string
	IsPrimary     bool
	Remarks       *string
	CreatedBy     uuid.UUID
}

// Validate validates create account parameters
func (p CreateVendorAccountParams) Validate() error {
	if p.VendorID == uuid.Nil {
		return ErrInvalidVendorID
	}
	if p.AccountName == "" {
		return ErrInvalidAccountName
	}
	if p.AccountNumber == "" {
		return ErrInvalidAccountNumber
	}
	if p.NameOfBank == "" {
		return ErrInvalidBankName
	}
	if p.IFSCCode == "" {
		return ErrInvalidIFSCCode
	}
	if !isValidIFSC(p.IFSCCode) {
		return ErrInvalidIFSCFormat
	}
	if p.CreatedBy == uuid.Nil {
		return ErrInvalidCreatedBy
	}
	return nil
}

// SetPrimary sets account as primary
func (va *VendorAccount) SetPrimary() {
	va.IsPrimary = true
	va.UpdatedAt = time.Now()
}

// UnsetPrimary removes primary status
func (va *VendorAccount) UnsetPrimary() {
	va.IsPrimary = false
	va.UpdatedAt = time.Now()
}

// ToggleStatus toggles account status
func (va *VendorAccount) ToggleStatus() {
	va.IsActive = !va.IsActive
	va.UpdatedAt = time.Now()
}

// Update updates account fields
func (va *VendorAccount) Update(params UpdateVendorAccountParams) error {
	if err := params.Validate(); err != nil {
		return err
	}

	if params.AccountName != nil {
		va.AccountName = *params.AccountName
	}
	if params.AccountNumber != nil {
		va.AccountNumber = *params.AccountNumber
	}
	if params.NameOfBank != nil {
		va.NameOfBank = *params.NameOfBank
	}
	if params.IFSCCode != nil {
		va.IFSCCode = *params.IFSCCode
	}
	if params.IsPrimary != nil {
		va.IsPrimary = *params.IsPrimary
	}
	if params.IsActive != nil {
		va.IsActive = *params.IsActive
	}

	va.UpdatedAt = time.Now()
	return nil
}

// UpdateVendorAccountParams holds parameters for updating account
type UpdateVendorAccountParams struct {
	AccountName   *string
	AccountNumber *string
	AccountType   *string
	NameOfBank    *string
	BranchName    *string
	IFSCCode      *string
	SwiftCode     *string
	IsPrimary     *bool
	IsActive      *bool
	Remarks       *string
}

// Validate validates update account parameters
func (p UpdateVendorAccountParams) Validate() error {
	if p.IFSCCode != nil && !isValidIFSC(*p.IFSCCode) {
		return ErrInvalidIFSCFormat
	}
	return nil
}

// Validation helper functions
func isValidEmail(email string) bool {
	emailRegex := regexp.MustCompile(`^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$`)
	return emailRegex.MatchString(email)
}

func isValidPAN(pan string) bool {
	panRegex := regexp.MustCompile(`^[A-Z]{5}[0-9]{4}[A-Z]{1}$`)
	return panRegex.MatchString(pan)
}

func isValidIFSC(ifsc string) bool {
	ifscRegex := regexp.MustCompile(`^[A-Z]{4}0[A-Z0-9]{6}$`)
	return ifscRegex.MatchString(ifsc)
}
