// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: api/proto/vendor.proto

package vendorpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VendorService_CreateVendor_FullMethodName            = "/vendor.v1.VendorService/CreateVendor"
	VendorService_GetVendor_FullMethodName               = "/vendor.v1.VendorService/GetVendor"
	VendorService_GetVendorByCode_FullMethodName         = "/vendor.v1.VendorService/GetVendorByCode"
	VendorService_UpdateVendor_FullMethodName            = "/vendor.v1.VendorService/UpdateVendor"
	VendorService_DeleteVendor_FullMethodName            = "/vendor.v1.VendorService/DeleteVendor"
	VendorService_ListVendors_FullMethodName             = "/vendor.v1.VendorService/ListVendors"
	VendorService_GenerateVendorCode_FullMethodName      = "/vendor.v1.VendorService/GenerateVendorCode"
	VendorService_UpdateVendorCode_FullMethodName        = "/vendor.v1.VendorService/UpdateVendorCode"
	VendorService_RegenerateVendorCode_FullMethodName    = "/vendor.v1.VendorService/RegenerateVendorCode"
	VendorService_CreateVendorAccount_FullMethodName     = "/vendor.v1.VendorService/CreateVendorAccount"
	VendorService_GetVendorAccounts_FullMethodName       = "/vendor.v1.VendorService/GetVendorAccounts"
	VendorService_GetVendorBankingDetails_FullMethodName = "/vendor.v1.VendorService/GetVendorBankingDetails"
	VendorService_UpdateVendorAccount_FullMethodName     = "/vendor.v1.VendorService/UpdateVendorAccount"
	VendorService_DeleteVendorAccount_FullMethodName     = "/vendor.v1.VendorService/DeleteVendorAccount"
	VendorService_ToggleAccountStatus_FullMethodName     = "/vendor.v1.VendorService/ToggleAccountStatus"
	VendorService_GetProjectsDropdown_FullMethodName     = "/vendor.v1.VendorService/GetProjectsDropdown"
	VendorService_UploadVendorSignature_FullMethodName   = "/vendor.v1.VendorService/UploadVendorSignature"
)

// VendorServiceClient is the client API for VendorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// VendorService provides vendor management operations
type VendorServiceClient interface {
	// Vendor operations
	CreateVendor(ctx context.Context, in *CreateVendorRequest, opts ...grpc.CallOption) (*VendorResponse, error)
	GetVendor(ctx context.Context, in *GetVendorRequest, opts ...grpc.CallOption) (*VendorResponse, error)
	GetVendorByCode(ctx context.Context, in *GetVendorByCodeRequest, opts ...grpc.CallOption) (*VendorResponse, error)
	UpdateVendor(ctx context.Context, in *UpdateVendorRequest, opts ...grpc.CallOption) (*VendorResponse, error)
	DeleteVendor(ctx context.Context, in *DeleteVendorRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListVendors(ctx context.Context, in *ListVendorsRequest, opts ...grpc.CallOption) (*ListVendorsResponse, error)
	// Vendor code operations
	GenerateVendorCode(ctx context.Context, in *GenerateVendorCodeRequest, opts ...grpc.CallOption) (*GenerateVendorCodeResponse, error)
	UpdateVendorCode(ctx context.Context, in *UpdateVendorCodeRequest, opts ...grpc.CallOption) (*VendorResponse, error)
	RegenerateVendorCode(ctx context.Context, in *RegenerateVendorCodeRequest, opts ...grpc.CallOption) (*VendorResponse, error)
	// Account operations
	CreateVendorAccount(ctx context.Context, in *CreateVendorAccountRequest, opts ...grpc.CallOption) (*VendorAccountResponse, error)
	GetVendorAccounts(ctx context.Context, in *GetVendorAccountsRequest, opts ...grpc.CallOption) (*GetVendorAccountsResponse, error)
	GetVendorBankingDetails(ctx context.Context, in *GetVendorBankingDetailsRequest, opts ...grpc.CallOption) (*BankingDetailsResponse, error)
	UpdateVendorAccount(ctx context.Context, in *UpdateVendorAccountRequest, opts ...grpc.CallOption) (*VendorAccountResponse, error)
	DeleteVendorAccount(ctx context.Context, in *DeleteVendorAccountRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ToggleAccountStatus(ctx context.Context, in *ToggleAccountStatusRequest, opts ...grpc.CallOption) (*VendorAccountResponse, error)
	// Dropdown endpoints
	GetProjectsDropdown(ctx context.Context, in *GetProjectsDropdownRequest, opts ...grpc.CallOption) (*GetProjectsDropdownResponse, error)
	// Upload Vendor Signature
	UploadVendorSignature(ctx context.Context, in *UploadVendorSignatureRequest, opts ...grpc.CallOption) (*UploadVendorSignatureResponse, error)
}

type vendorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVendorServiceClient(cc grpc.ClientConnInterface) VendorServiceClient {
	return &vendorServiceClient{cc}
}

func (c *vendorServiceClient) CreateVendor(ctx context.Context, in *CreateVendorRequest, opts ...grpc.CallOption) (*VendorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VendorResponse)
	err := c.cc.Invoke(ctx, VendorService_CreateVendor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendorServiceClient) GetVendor(ctx context.Context, in *GetVendorRequest, opts ...grpc.CallOption) (*VendorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VendorResponse)
	err := c.cc.Invoke(ctx, VendorService_GetVendor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendorServiceClient) GetVendorByCode(ctx context.Context, in *GetVendorByCodeRequest, opts ...grpc.CallOption) (*VendorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VendorResponse)
	err := c.cc.Invoke(ctx, VendorService_GetVendorByCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendorServiceClient) UpdateVendor(ctx context.Context, in *UpdateVendorRequest, opts ...grpc.CallOption) (*VendorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VendorResponse)
	err := c.cc.Invoke(ctx, VendorService_UpdateVendor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendorServiceClient) DeleteVendor(ctx context.Context, in *DeleteVendorRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, VendorService_DeleteVendor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendorServiceClient) ListVendors(ctx context.Context, in *ListVendorsRequest, opts ...grpc.CallOption) (*ListVendorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVendorsResponse)
	err := c.cc.Invoke(ctx, VendorService_ListVendors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendorServiceClient) GenerateVendorCode(ctx context.Context, in *GenerateVendorCodeRequest, opts ...grpc.CallOption) (*GenerateVendorCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateVendorCodeResponse)
	err := c.cc.Invoke(ctx, VendorService_GenerateVendorCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendorServiceClient) UpdateVendorCode(ctx context.Context, in *UpdateVendorCodeRequest, opts ...grpc.CallOption) (*VendorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VendorResponse)
	err := c.cc.Invoke(ctx, VendorService_UpdateVendorCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendorServiceClient) RegenerateVendorCode(ctx context.Context, in *RegenerateVendorCodeRequest, opts ...grpc.CallOption) (*VendorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VendorResponse)
	err := c.cc.Invoke(ctx, VendorService_RegenerateVendorCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendorServiceClient) CreateVendorAccount(ctx context.Context, in *CreateVendorAccountRequest, opts ...grpc.CallOption) (*VendorAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VendorAccountResponse)
	err := c.cc.Invoke(ctx, VendorService_CreateVendorAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendorServiceClient) GetVendorAccounts(ctx context.Context, in *GetVendorAccountsRequest, opts ...grpc.CallOption) (*GetVendorAccountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVendorAccountsResponse)
	err := c.cc.Invoke(ctx, VendorService_GetVendorAccounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendorServiceClient) GetVendorBankingDetails(ctx context.Context, in *GetVendorBankingDetailsRequest, opts ...grpc.CallOption) (*BankingDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BankingDetailsResponse)
	err := c.cc.Invoke(ctx, VendorService_GetVendorBankingDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendorServiceClient) UpdateVendorAccount(ctx context.Context, in *UpdateVendorAccountRequest, opts ...grpc.CallOption) (*VendorAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VendorAccountResponse)
	err := c.cc.Invoke(ctx, VendorService_UpdateVendorAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendorServiceClient) DeleteVendorAccount(ctx context.Context, in *DeleteVendorAccountRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, VendorService_DeleteVendorAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendorServiceClient) ToggleAccountStatus(ctx context.Context, in *ToggleAccountStatusRequest, opts ...grpc.CallOption) (*VendorAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VendorAccountResponse)
	err := c.cc.Invoke(ctx, VendorService_ToggleAccountStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendorServiceClient) GetProjectsDropdown(ctx context.Context, in *GetProjectsDropdownRequest, opts ...grpc.CallOption) (*GetProjectsDropdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProjectsDropdownResponse)
	err := c.cc.Invoke(ctx, VendorService_GetProjectsDropdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendorServiceClient) UploadVendorSignature(ctx context.Context, in *UploadVendorSignatureRequest, opts ...grpc.CallOption) (*UploadVendorSignatureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadVendorSignatureResponse)
	err := c.cc.Invoke(ctx, VendorService_UploadVendorSignature_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VendorServiceServer is the server API for VendorService service.
// All implementations must embed UnimplementedVendorServiceServer
// for forward compatibility.
//
// VendorService provides vendor management operations
type VendorServiceServer interface {
	// Vendor operations
	CreateVendor(context.Context, *CreateVendorRequest) (*VendorResponse, error)
	GetVendor(context.Context, *GetVendorRequest) (*VendorResponse, error)
	GetVendorByCode(context.Context, *GetVendorByCodeRequest) (*VendorResponse, error)
	UpdateVendor(context.Context, *UpdateVendorRequest) (*VendorResponse, error)
	DeleteVendor(context.Context, *DeleteVendorRequest) (*emptypb.Empty, error)
	ListVendors(context.Context, *ListVendorsRequest) (*ListVendorsResponse, error)
	// Vendor code operations
	GenerateVendorCode(context.Context, *GenerateVendorCodeRequest) (*GenerateVendorCodeResponse, error)
	UpdateVendorCode(context.Context, *UpdateVendorCodeRequest) (*VendorResponse, error)
	RegenerateVendorCode(context.Context, *RegenerateVendorCodeRequest) (*VendorResponse, error)
	// Account operations
	CreateVendorAccount(context.Context, *CreateVendorAccountRequest) (*VendorAccountResponse, error)
	GetVendorAccounts(context.Context, *GetVendorAccountsRequest) (*GetVendorAccountsResponse, error)
	GetVendorBankingDetails(context.Context, *GetVendorBankingDetailsRequest) (*BankingDetailsResponse, error)
	UpdateVendorAccount(context.Context, *UpdateVendorAccountRequest) (*VendorAccountResponse, error)
	DeleteVendorAccount(context.Context, *DeleteVendorAccountRequest) (*emptypb.Empty, error)
	ToggleAccountStatus(context.Context, *ToggleAccountStatusRequest) (*VendorAccountResponse, error)
	// Dropdown endpoints
	GetProjectsDropdown(context.Context, *GetProjectsDropdownRequest) (*GetProjectsDropdownResponse, error)
	// Upload Vendor Signature
	UploadVendorSignature(context.Context, *UploadVendorSignatureRequest) (*UploadVendorSignatureResponse, error)
	mustEmbedUnimplementedVendorServiceServer()
}

// UnimplementedVendorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVendorServiceServer struct{}

func (UnimplementedVendorServiceServer) CreateVendor(context.Context, *CreateVendorRequest) (*VendorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVendor not implemented")
}
func (UnimplementedVendorServiceServer) GetVendor(context.Context, *GetVendorRequest) (*VendorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVendor not implemented")
}
func (UnimplementedVendorServiceServer) GetVendorByCode(context.Context, *GetVendorByCodeRequest) (*VendorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVendorByCode not implemented")
}
func (UnimplementedVendorServiceServer) UpdateVendor(context.Context, *UpdateVendorRequest) (*VendorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateVendor not implemented")
}
func (UnimplementedVendorServiceServer) DeleteVendor(context.Context, *DeleteVendorRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteVendor not implemented")
}
func (UnimplementedVendorServiceServer) ListVendors(context.Context, *ListVendorsRequest) (*ListVendorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListVendors not implemented")
}
func (UnimplementedVendorServiceServer) GenerateVendorCode(context.Context, *GenerateVendorCodeRequest) (*GenerateVendorCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateVendorCode not implemented")
}
func (UnimplementedVendorServiceServer) UpdateVendorCode(context.Context, *UpdateVendorCodeRequest) (*VendorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateVendorCode not implemented")
}
func (UnimplementedVendorServiceServer) RegenerateVendorCode(context.Context, *RegenerateVendorCodeRequest) (*VendorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegenerateVendorCode not implemented")
}
func (UnimplementedVendorServiceServer) CreateVendorAccount(context.Context, *CreateVendorAccountRequest) (*VendorAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVendorAccount not implemented")
}
func (UnimplementedVendorServiceServer) GetVendorAccounts(context.Context, *GetVendorAccountsRequest) (*GetVendorAccountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVendorAccounts not implemented")
}
func (UnimplementedVendorServiceServer) GetVendorBankingDetails(context.Context, *GetVendorBankingDetailsRequest) (*BankingDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVendorBankingDetails not implemented")
}
func (UnimplementedVendorServiceServer) UpdateVendorAccount(context.Context, *UpdateVendorAccountRequest) (*VendorAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateVendorAccount not implemented")
}
func (UnimplementedVendorServiceServer) DeleteVendorAccount(context.Context, *DeleteVendorAccountRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteVendorAccount not implemented")
}
func (UnimplementedVendorServiceServer) ToggleAccountStatus(context.Context, *ToggleAccountStatusRequest) (*VendorAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ToggleAccountStatus not implemented")
}
func (UnimplementedVendorServiceServer) GetProjectsDropdown(context.Context, *GetProjectsDropdownRequest) (*GetProjectsDropdownResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProjectsDropdown not implemented")
}
func (UnimplementedVendorServiceServer) UploadVendorSignature(context.Context, *UploadVendorSignatureRequest) (*UploadVendorSignatureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadVendorSignature not implemented")
}
func (UnimplementedVendorServiceServer) mustEmbedUnimplementedVendorServiceServer() {}
func (UnimplementedVendorServiceServer) testEmbeddedByValue()                       {}

// UnsafeVendorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VendorServiceServer will
// result in compilation errors.
type UnsafeVendorServiceServer interface {
	mustEmbedUnimplementedVendorServiceServer()
}

func RegisterVendorServiceServer(s grpc.ServiceRegistrar, srv VendorServiceServer) {
	// If the following call pancis, it indicates UnimplementedVendorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VendorService_ServiceDesc, srv)
}

func _VendorService_CreateVendor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVendorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorServiceServer).CreateVendor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VendorService_CreateVendor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorServiceServer).CreateVendor(ctx, req.(*CreateVendorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VendorService_GetVendor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVendorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorServiceServer).GetVendor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VendorService_GetVendor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorServiceServer).GetVendor(ctx, req.(*GetVendorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VendorService_GetVendorByCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVendorByCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorServiceServer).GetVendorByCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VendorService_GetVendorByCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorServiceServer).GetVendorByCode(ctx, req.(*GetVendorByCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VendorService_UpdateVendor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateVendorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorServiceServer).UpdateVendor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VendorService_UpdateVendor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorServiceServer).UpdateVendor(ctx, req.(*UpdateVendorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VendorService_DeleteVendor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVendorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorServiceServer).DeleteVendor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VendorService_DeleteVendor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorServiceServer).DeleteVendor(ctx, req.(*DeleteVendorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VendorService_ListVendors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVendorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorServiceServer).ListVendors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VendorService_ListVendors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorServiceServer).ListVendors(ctx, req.(*ListVendorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VendorService_GenerateVendorCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateVendorCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorServiceServer).GenerateVendorCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VendorService_GenerateVendorCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorServiceServer).GenerateVendorCode(ctx, req.(*GenerateVendorCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VendorService_UpdateVendorCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateVendorCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorServiceServer).UpdateVendorCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VendorService_UpdateVendorCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorServiceServer).UpdateVendorCode(ctx, req.(*UpdateVendorCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VendorService_RegenerateVendorCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegenerateVendorCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorServiceServer).RegenerateVendorCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VendorService_RegenerateVendorCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorServiceServer).RegenerateVendorCode(ctx, req.(*RegenerateVendorCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VendorService_CreateVendorAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVendorAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorServiceServer).CreateVendorAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VendorService_CreateVendorAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorServiceServer).CreateVendorAccount(ctx, req.(*CreateVendorAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VendorService_GetVendorAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVendorAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorServiceServer).GetVendorAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VendorService_GetVendorAccounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorServiceServer).GetVendorAccounts(ctx, req.(*GetVendorAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VendorService_GetVendorBankingDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVendorBankingDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorServiceServer).GetVendorBankingDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VendorService_GetVendorBankingDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorServiceServer).GetVendorBankingDetails(ctx, req.(*GetVendorBankingDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VendorService_UpdateVendorAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateVendorAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorServiceServer).UpdateVendorAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VendorService_UpdateVendorAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorServiceServer).UpdateVendorAccount(ctx, req.(*UpdateVendorAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VendorService_DeleteVendorAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVendorAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorServiceServer).DeleteVendorAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VendorService_DeleteVendorAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorServiceServer).DeleteVendorAccount(ctx, req.(*DeleteVendorAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VendorService_ToggleAccountStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToggleAccountStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorServiceServer).ToggleAccountStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VendorService_ToggleAccountStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorServiceServer).ToggleAccountStatus(ctx, req.(*ToggleAccountStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VendorService_GetProjectsDropdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectsDropdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorServiceServer).GetProjectsDropdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VendorService_GetProjectsDropdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorServiceServer).GetProjectsDropdown(ctx, req.(*GetProjectsDropdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VendorService_UploadVendorSignature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadVendorSignatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorServiceServer).UploadVendorSignature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VendorService_UploadVendorSignature_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorServiceServer).UploadVendorSignature(ctx, req.(*UploadVendorSignatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VendorService_ServiceDesc is the grpc.ServiceDesc for VendorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VendorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vendor.v1.VendorService",
	HandlerType: (*VendorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVendor",
			Handler:    _VendorService_CreateVendor_Handler,
		},
		{
			MethodName: "GetVendor",
			Handler:    _VendorService_GetVendor_Handler,
		},
		{
			MethodName: "GetVendorByCode",
			Handler:    _VendorService_GetVendorByCode_Handler,
		},
		{
			MethodName: "UpdateVendor",
			Handler:    _VendorService_UpdateVendor_Handler,
		},
		{
			MethodName: "DeleteVendor",
			Handler:    _VendorService_DeleteVendor_Handler,
		},
		{
			MethodName: "ListVendors",
			Handler:    _VendorService_ListVendors_Handler,
		},
		{
			MethodName: "GenerateVendorCode",
			Handler:    _VendorService_GenerateVendorCode_Handler,
		},
		{
			MethodName: "UpdateVendorCode",
			Handler:    _VendorService_UpdateVendorCode_Handler,
		},
		{
			MethodName: "RegenerateVendorCode",
			Handler:    _VendorService_RegenerateVendorCode_Handler,
		},
		{
			MethodName: "CreateVendorAccount",
			Handler:    _VendorService_CreateVendorAccount_Handler,
		},
		{
			MethodName: "GetVendorAccounts",
			Handler:    _VendorService_GetVendorAccounts_Handler,
		},
		{
			MethodName: "GetVendorBankingDetails",
			Handler:    _VendorService_GetVendorBankingDetails_Handler,
		},
		{
			MethodName: "UpdateVendorAccount",
			Handler:    _VendorService_UpdateVendorAccount_Handler,
		},
		{
			MethodName: "DeleteVendorAccount",
			Handler:    _VendorService_DeleteVendorAccount_Handler,
		},
		{
			MethodName: "ToggleAccountStatus",
			Handler:    _VendorService_ToggleAccountStatus_Handler,
		},
		{
			MethodName: "GetProjectsDropdown",
			Handler:    _VendorService_GetProjectsDropdown_Handler,
		},
		{
			MethodName: "UploadVendorSignature",
			Handler:    _VendorService_UploadVendorSignature_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/vendor.proto",
}
